% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={M2.851 -- TIPOLOGÍA Y CICLO DE VIDA DE LOS DATOS: PRA 2},
  pdfauthor={Olga Garcés Ciemerozum / Carlos Acosta Quintas},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{48,48,48}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{1.00,0.81,0.69}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.50,0.62,0.50}{\textbf{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.80,0.80,0.80}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.86,0.64,0.64}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.80,0.80,0.80}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.86,0.64,0.64}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.50,0.62,0.50}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.50,0.62,0.50}{\textbf{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.86,0.64,0.64}{\textbf{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.94,0.87,0.69}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.87,0.87,0.75}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.86,0.86,0.80}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.50,0.62,0.50}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.76,0.75,0.62}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.80,0.80,0.80}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.75,0.75,0.82}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.94,0.94,0.56}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.80,0.80,0.80}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.50,0.62,0.50}{\textbf{#1}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.94,0.87,0.69}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.80,0.80,0.80}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.94,0.94,0.82}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.94,0.94,0.56}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{1.00,0.81,0.69}{\textbf{#1}}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.80,0.80,0.80}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.86,0.64,0.64}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.80,0.58,0.58}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.80,0.58,0.58}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.80,0.80,0.80}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.80,0.58,0.58}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.50,0.62,0.50}{\textbf{#1}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\title{\textbf{M2.851 -- TIPOLOGÍA Y CICLO DE VIDA DE LOS DATOS: PRA 2}}
\author{Olga Garcés Ciemerozum / Carlos Acosta Quintas}
\date{Junio 2021}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
Introducción

El presente informe forma parte de la segunda práctica de la asignatura
M2.851 - Tipología y ciclo de vida de los datos del Máster Universitario
en Ciencia de Datos impartido por la Universitat Oberta de Catalunya.

En esta práctica se realizarán técnicas de limpieza de datos aplicadas a
un juego de datos determinado y también se analizarán dichos datos para
extraer información relevante y útil.

A su vez, se entregará, junto con la presente memoria, una serie de
archivos con el código necesario para la realización de la limpieza y
análisis con el que el usuario podrá realizar diferentes estudios
analíticos a posteriori si lo desease.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{descripciuxf3n-del-dataset.-por-quuxe9-es-importante-y-quuxe9-preguntaproblema-pretende-responder}{%
\section{\texorpdfstring{\textbf{Descripción del dataset. ¿Por qué es
importante y qué pregunta/problema pretende
responder?}}{Descripción del dataset. ¿Por qué es importante y qué pregunta/problema pretende responder?}}\label{descripciuxf3n-del-dataset.-por-quuxe9-es-importante-y-quuxe9-preguntaproblema-pretende-responder}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{descripciuxf3n-del-dataset}{%
\subsection{\texorpdfstring{\textbf{Descripción del
dataset}}{Descripción del dataset}}\label{descripciuxf3n-del-dataset}}

El dataset Titanic reune los datos sobre los pasajeros que viajaban a
bordo del Titanic y registra para cada persona su supervivencia o no en
el accidente. El Titanic transportaba a pasajeros con gran diversidad en
sus niveles de renta y edad y a bordo se encontraban familias enteras.

La etiqueta (variable a predecir) es la variable dicotómica que indica
si el viajero ha sobrevivido o no.

La ubicación en kaggle del dataset utilizado se muestra en el siguiente
link:

\url{https://www.kaggle.com/c/titanic/data}

Los archivos disponibles son 3 y están en formato csv. Sus nombres son:

• train.csv\\
• test.csv\\
• gender\_submission.csv: Ejemplo a seguir en la entrega de la
competición Kaggle (no útil).

Según los registros, en el Titanic viajaban 2229 personas, de las cuales
913 formaban parte de la tripulación del barco. El dataset que obtenemos
de Kaggle tiene un total de 1309 registros, por lo tanto, no todos los
pasajeros que viajaban a bordo están incluidos en el dataset y podemos
asumir que el juego de datos es una muestra de toda la población a
analizar.

El dataset original está compuesto por dos ficheros: el fichero pensado
para realizar el entrenamiento de un modelo (train.csv) y el fichero con
los datos destinados a testear la calidad del modelo (test.csv). El
fichero de entrenamiento contiene una columna más que el fichero de
prueba. Esta columna corresponde a la columna de la clase ``Survived''.

El fichero de entrenamiento tiene 891 registros mientras que el fichero
de test contiene 418 instancias.

Las variables de las que se compone el dataset son y sus unidades o
magnitudes de las características son:

\textbf{PassengerId}:\\
Identificador del pasajero\\
Tipo: Entero indicando un identificador único de casa instancia.

\textbf{Survived}:\\
Indica si el pasajero ha sobrevivido la catástrofe\\
Tipo: Entero (categórica) 0 = No ha sobrevivido; 1 = Ha sobrevivido

\textbf{Pclass}:\\
Clase en la que viajaba el pasajero\\
Tipo: String (categórica) 1 = 1 a clase; 2 = 2 a clase; 3 = 3a clase

\textbf{Name}:\\
Nombre del pasajero\\
Tipo: String

\textbf{Sex}:\\
Sexo del pasajero\\
Tipo: String (categórica) female = Mujer; male = hombre

\textbf{Age}:\\
Edad del pasajero\\
Tipo: Entero

\textbf{SibSp}:\\
Indica si el pasajero tenía hermanos o pareja a bordo\\
Tipo: Entero

\textbf{Parch}:\\
Indica si el pasajero tenía padres o hijos a bordo\\
Tipo: Entero

\textbf{Ticket}:\\
Número del billete\\
Tipo: String alfanumérico

\textbf{Fare}:\\
Precio del billete sin especificar si es un billete individual o
grupal\\
Tipo: Número Real

\textbf{Cabin}:\\
Número de camarote\\
Tipo: String

\textbf{Embarked}:\\
Indica si el pasajero ha embarcado o no y donde\\
Tipo: String (categórica) C = Cherbourg, Q = Queenstown, S = Southampton

Los datos no han pasado por un proceso de preprocesado o limpieza, por
lo que aún pueden existir inconsistencias y el formato no es
necesariamente el más adecuado para un análisis directo.

\textbf{Carga del dataset}:

Cargamos el dataset y mostramos sus dimensiones, estructura y tipo de
datos:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Carga de los archivos que contienen los datos del train y test}
\NormalTok{test <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"titanic/test.csv"}\NormalTok{)}
\NormalTok{train <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"titanic/train.csv"}\NormalTok{)}

\NormalTok{train_rows <-}\StringTok{ }\KeywordTok{dim}\NormalTok{(train)}
\NormalTok{test_rows <-}\StringTok{ }\KeywordTok{dim}\NormalTok{(test)}

\NormalTok{train_rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 891  12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test_rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 418  11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Estructura de los archivos train.csv y test.csv}
\KeywordTok{str}\NormalTok{(train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    891 obs. of  12 variables:
##  $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
##  $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
##  $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
##  $ Sex        : chr  "male" "female" "female" "female" ...
##  $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
##  $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
##  $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
##  $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
##  $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
##  $ Cabin      : chr  "" "C85" "" "C123" ...
##  $ Embarked   : chr  "S" "C" "S" "S" ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    418 obs. of  11 variables:
##  $ PassengerId: int  892 893 894 895 896 897 898 899 900 901 ...
##  $ Pclass     : int  3 3 2 3 3 3 3 2 3 3 ...
##  $ Name       : chr  "Kelly, Mr. James" "Wilkes, Mrs. James (Ellen Needs)" "Myles, Mr. Thomas Francis" "Wirz, Mr. Albert" ...
##  $ Sex        : chr  "male" "female" "male" "male" ...
##  $ Age        : num  34.5 47 62 27 22 14 30 26 18 21 ...
##  $ SibSp      : int  0 1 0 0 1 0 0 1 0 2 ...
##  $ Parch      : int  0 0 0 0 1 0 0 1 0 0 ...
##  $ Ticket     : chr  "330911" "363272" "240276" "315154" ...
##  $ Fare       : num  7.83 7 9.69 8.66 12.29 ...
##  $ Cabin      : chr  "" "" "" "" ...
##  $ Embarked   : chr  "Q" "S" "Q" "S" ...
\end{verbatim}

Visualizamos las primeras líneas del conjunto de entrenamiento y de
test.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Primeras líneas del conjunto de entrenamiento y de test.}
\KeywordTok{head}\NormalTok{(train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   PassengerId Survived Pclass                                                Name    Sex Age SibSp Parch           Ticket    Fare Cabin Embarked
## 1           1        0      3                             Braund, Mr. Owen Harris   male  22     1     0        A/5 21171  7.2500              S
## 2           2        1      1 Cumings, Mrs. John Bradley (Florence Briggs Thayer) female  38     1     0         PC 17599 71.2833   C85        C
## 3           3        1      3                              Heikkinen, Miss. Laina female  26     0     0 STON/O2. 3101282  7.9250              S
## 4           4        1      1        Futrelle, Mrs. Jacques Heath (Lily May Peel) female  35     1     0           113803 53.1000  C123        S
## 5           5        0      3                            Allen, Mr. William Henry   male  35     0     0           373450  8.0500              S
## 6           6        0      3                                    Moran, Mr. James   male  NA     0     0           330877  8.4583              Q
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(test)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   PassengerId Pclass                                         Name    Sex  Age SibSp Parch  Ticket    Fare Cabin Embarked
## 1         892      3                             Kelly, Mr. James   male 34.5     0     0  330911  7.8292              Q
## 2         893      3             Wilkes, Mrs. James (Ellen Needs) female 47.0     1     0  363272  7.0000              S
## 3         894      2                    Myles, Mr. Thomas Francis   male 62.0     0     0  240276  9.6875              Q
## 4         895      3                             Wirz, Mr. Albert   male 27.0     0     0  315154  8.6625              S
## 5         896      3 Hirvonen, Mrs. Alexander (Helga E Lindqvist) female 22.0     1     1 3101298 12.2875              S
## 6         897      3                   Svensson, Mr. Johan Cervin   male 14.0     0     0    7538  9.2250              S
\end{verbatim}

\hypertarget{por-quuxe9-es-importante-el-dataset}{%
\subsection{\texorpdfstring{\textbf{¿Por qué es importante el
dataset?}}{¿Por qué es importante el dataset?}}\label{por-quuxe9-es-importante-el-dataset}}

Este dataset es importante porque nos permite esclarecer qué factores
pudieron influir en la supervivencia de viajeros del Titanic y obtener
el conocimiento necesario para poder hacer predicciones con nuevas
instancias.

Estos factores intuimos que pueden ser el estatus social, el sexo, la
edad y también tener familiares cerca.

Asimismo, podemos ver si las pautas marcadas por la sociedad de
``mujeres y niños primero'' se cumplen cuando las personas se encuentran
en situaciones de estres extremo.

De igual forma, y en el ámbito de la ciencia de datos, este dataset es
importante porque es considerado un clásico y ha ayudado a muchos
estudiantes a enfrentarse por primera vez a un problema de limpieza de
datos, análisis estadísticos e incluso a técnicas de machine learning.

\hypertarget{quuxe9-problema-pretende-responder-el-dataset}{%
\subsection{\texorpdfstring{\textbf{¿Qué problema pretende responder el
dataset?}}{¿Qué problema pretende responder el dataset?}}\label{quuxe9-problema-pretende-responder-el-dataset}}

Este dataset pretende responder a cuáles son los diferentes factores que
afectaron a la posibilidad de supervivencia de personas en el accidente
del Titanic.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{integraciuxf3n-y-selecciuxf3n-de-los-datos}{%
\section{\texorpdfstring{\textbf{Integración y selección de los
datos}}{Integración y selección de los datos}}\label{integraciuxf3n-y-selecciuxf3n-de-los-datos}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{integraciuxf3n-de-los-datos}{%
\subsection{\texorpdfstring{\textbf{Integración de los
Datos}}{Integración de los Datos}}\label{integraciuxf3n-de-los-datos}}

La integración es un proceso que forma parte de la fase de limpieza de
datos y se entiende como la fusión de datos para crear una estructura
única que tenga la información necesaria para el posterior análisis de
datos.

Existe la integración horizontal, que básicamente se compone de la
adición de nuevos atributos a partir de otras fuentes mediante sus
relaciones usando claves primarias y la integración vertical, que se
basaría en añadir más instancias al juego de datos (siempre manteniendo
la integridad de los atributos).

En nuestro caso, tenemos dos archivos train.csv y test.csv, dónde la
diferencia entre ambos es que el test no tiene las etiquetas de la
variable ``Survived''.

\textbf{Integración Vertical}:

Con la finalidad de observar las distribuciones de las variables que
serán base del estudio en la predicción de ``Survived'' integraremos
verticalmente los dos archivos y así obtendremos un mayor número de
datos para ver sus medidas de tendencia central y dispersión.

Para que la integración vertical sea satisfactoria, las variables y
estructura de ambos archivos debe coincidir, por tanto, crearemos un
dataframe train\_sin\_etiqueta que se integrará con las instancias de
test.csv al cual llamaremos df\_total\_sin\_etiqueta.

Observamos que la integración es satisfactoria puesto que las instancias
ahora son 1309 (891 + 418).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creación archivo train_sin_etiqueta.csv}

\NormalTok{etiquetas <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(train, }\DataTypeTok{select =}\NormalTok{ Survived)}
\NormalTok{train_sin_etiqueta <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(train, }\DataTypeTok{select =} \OperatorTok{-}\NormalTok{Survived)}

\CommentTok{# Integración archivos train.csv y test.csv}
\NormalTok{df_total_sin_etiqueta =}\StringTok{ }\KeywordTok{rbind}\NormalTok{(train_sin_etiqueta, test)}
\KeywordTok{dim}\NormalTok{(df_total_sin_etiqueta)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1309   11
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Guardamos el archivo con el nombre Titanic_global_sin_etiqueta.csv}
\KeywordTok{write.csv}\NormalTok{(df_total_sin_etiqueta, }\StringTok{"Titanic_global_sin_etiqueta.csv"}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{Integración Horizontal}:

Los archivos en la plataforma Kaggle no exponen ni fuentes externas ni
csv adicionales que definan nuevas variables que se puedan integrar
horizontalmente a nuestro juego de datos.

\textbf{Comprobación de líneas duplicadas}:

Comprobamos si hay líneas duplicadas en el dataframe usando
\texttt{duplicated}. No existen registros duplicados, pero sí detectamos
dos pares de personas con el mismo nombre. Para asegurarnos que se trata
de personas diferentes, buscamos los registros que tengan los nombres
Connolly, Miss. Kate o Kelly, Mr.~James.

Podría tratarse de la misma persona que ha comprado dos billetes, pero
en estos registros vemos que las personas tienen edades diferentes y no
hay motivo para pensar que se trata de duplicados.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Chequeo de líneas duplicadas}
\NormalTok{df_total_sin_etiqueta[}\KeywordTok{duplicated}\NormalTok{(df_total_sin_etiqueta),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] PassengerId Pclass      Name        Sex         Age         SibSp       Parch       Ticket      Fare        Cabin       Embarked   
## <0 rows> (or 0-length row.names)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_total_sin_etiqueta[}\KeywordTok{duplicated}\NormalTok{(df_total_sin_etiqueta[}\KeywordTok{c}\NormalTok{(}\StringTok{"Name"}\NormalTok{,}\StringTok{"Sex"}\NormalTok{)]),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     PassengerId Pclass                 Name    Sex  Age SibSp Parch Ticket   Fare Cabin Embarked
## 892         892      3     Kelly, Mr. James   male 34.5     0     0 330911 7.8292              Q
## 898         898      3 Connolly, Miss. Kate female 30.0     0     0 330972 7.6292              Q
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_total_sin_etiqueta[df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Name}\OperatorTok{==}\StringTok{"Kelly, Mr. James"} \OperatorTok{|}\StringTok{ }\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Name }\OperatorTok{==}\StringTok{ "Connolly, Miss. Kate"}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     PassengerId Pclass                 Name    Sex  Age SibSp Parch Ticket   Fare Cabin Embarked
## 290         290      3 Connolly, Miss. Kate female 22.0     0     0 370373 7.7500              Q
## 697         697      3     Kelly, Mr. James   male 44.0     0     0 363592 8.0500              S
## 892         892      3     Kelly, Mr. James   male 34.5     0     0 330911 7.8292              Q
## 898         898      3 Connolly, Miss. Kate female 30.0     0     0 330972 7.6292              Q
\end{verbatim}

\hypertarget{selecciuxf3n-de-los-datos}{%
\subsection{\texorpdfstring{\textbf{Selección de los
Datos}}{Selección de los Datos}}\label{selecciuxf3n-de-los-datos}}

La selección se puede entender como un primer filtro de los datos, no
solamente a través de poner límites a los valores de algunas instancias
o elegir algún valor cualitativo específico, sino también a través de la
inspección de las correlaciones entre los atributos y la posterior
eliminación del dataset de aquellos que sean redundantes.

Debido a que el problema planteado es interpretar qué factores influyen
en la supervivencia, a priori, no sabríamos si debemos descartar alguna
variable o no (eliminación de la variable del estudio) o si deberíamos
filtrar los datos, ya sean numérica o categóricamente.

No obstante, en esta sección eliminaremos la variable ``Name'' porque no
es de mucha utilidad para nuestros análisis ya que el nombre no debería
influir a priori en la supervivencia de los viajeros y también la
variable ``PassengerId'' puesto que simplemente es un identificador.

Por lo tanto, además de esta primera selección relizada, esta fase del
proceso la dejaremos abierta en este punto y retomaremos una vez la
exploración y análisis nos vaya indicando qué debemos seleccionar y/o
filtrar. A continuación, se hace una lista de las selecciones realizadas
en este apartado y a posteriori.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Eliminamos variables Name}
\NormalTok{keep.cols <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Pclass"}\NormalTok{, }\StringTok{"Sex"}\NormalTok{, }\StringTok{"Age"}\NormalTok{, }\StringTok{"SibSp"}\NormalTok{, }\StringTok{"Parch"}\NormalTok{, }\StringTok{"Ticket"}\NormalTok{, }\StringTok{"Fare"}\NormalTok{, }\StringTok{"Cabin"}\NormalTok{, }\StringTok{"Embarked"}\NormalTok{)}
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[keep.cols]}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}llll@{}}
\toprule
Variable Modificada & Tipo de selección & Apartado realizado &
Motivo\tabularnewline
\midrule
\endhead
Name & Eliminación & 2.2 & Variable no útil al ser independiente al
estudio\tabularnewline
PassengerId & Eliminación & 2.2 & Variable no útil al ser un simple
identificador\tabularnewline
Ticket & Eliminación & 2.3 & Usada para crear nueva variable y ya no es
útil\tabularnewline
Fase & Eliminación & 2.3 & Usada para crear nueva variable y ya no es
útil\tabularnewline
Cabin & Eliminación & 3.1 & Existencia masiva de valores
nulos\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{creaciuxf3n-de-nuevas-variables}{%
\subsection{\texorpdfstring{\textbf{Creación de nuevas
variables}}{Creación de nuevas variables}}\label{creaciuxf3n-de-nuevas-variables}}

Se ha detectado que hay números de billetes duplicados. Esto indica que
hay dos tipos de tickets:

• Individuales\\
• Grupales

Se observa que la variable ``Fare'' muestra el mismo precio para los
tickets grupales, por tanto, para saber realmente el precio del ticket
por viajero y también para poder usar correctamente la variable
``Fare'', deberíamos saber de cuántas personas es el ticket grupal y
después dividir la variable ``Fare'' for dicha cantidad.

Crearemos una columna con el recuento de billetes con el mismo id para
cada pasajero y otra con el precio unitario.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creación variable con el contaje de los tickets con mismo nombre}
\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Count.ticket <-}\StringTok{ }\NormalTok{(df_total_sin_etiqueta}\OperatorTok{%>%}\KeywordTok{group_by}\NormalTok{(Ticket)}\OperatorTok{%>%}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{count=}\KeywordTok{n}\NormalTok{()))}\OperatorTok{$}\NormalTok{count}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creación variable con el precio unitariocontaje de los tickets con mismo nombre}
\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Fare }\OperatorTok{/}\StringTok{ }\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Count.ticket}
\end{Highlighting}
\end{Shaded}

Selección de datos inicial a posteriori

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Eliminamos variable Name}
\NormalTok{keep.cols <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Pclass"}\NormalTok{, }\StringTok{"Sex"}\NormalTok{, }\StringTok{"Age"}\NormalTok{, }\StringTok{"SibSp"}\NormalTok{, }\StringTok{"Parch"}\NormalTok{, }\StringTok{"Cabin"}\NormalTok{, }\StringTok{"Embarked"}\NormalTok{, }\StringTok{"Count.ticket"}\NormalTok{, }\StringTok{"Unit.price"}\NormalTok{)}
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[keep.cols]}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{limpieza-de-datos}{%
\section{\texorpdfstring{\textbf{Limpieza de
datos}}{Limpieza de datos}}\label{limpieza-de-datos}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Hay que mencionar que se la limpieza de datos en este proyecto en
particular debe afectar tanto al archivo train.csv como al test.csv, por
tanto, limpiaremos los datos en base al dataframe global creado
anteriormente (df\_total\_sin\_etiqueta).

\hypertarget{los-datos-contienen-ceros-o-elementos-vacuxedos-cuxf3mo-gestionaruxedas-cada-uno-de-estos-casos}{%
\subsection{\texorpdfstring{\textbf{¿Los datos contienen ceros o
elementos vacíos? ¿Cómo gestionarías cada uno de estos
casos?}}{¿Los datos contienen ceros o elementos vacíos? ¿Cómo gestionarías cada uno de estos casos?}}\label{los-datos-contienen-ceros-o-elementos-vacuxedos-cuxf3mo-gestionaruxedas-cada-uno-de-estos-casos}}

\hypertarget{elementos-vacuxedos-en-el-dataset}{%
\subsubsection{\texorpdfstring{\textbf{Elementos vacíos en el
dataset}}{Elementos vacíos en el dataset}}\label{elementos-vacuxedos-en-el-dataset}}

Comprobaremos si existen valores nulos o inexistentes en el juego de
datos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Overview of the data - Type = 1}
\KeywordTok{ExpData}\NormalTok{(}\DataTypeTok{data=}\NormalTok{df_total_sin_etiqueta,}\DataTypeTok{type=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                                           Descriptions      Value
## 1                                   Sample size (nrow)       1309
## 2                              No. of variables (ncol)          9
## 3                    No. of numeric/interger variables          6
## 4                              No. of factor variables          0
## 5                                No. of text variables          3
## 6                             No. of logical variables          0
## 7                          No. of identifier variables          0
## 8                                No. of date variables          0
## 9             No. of zero variance variables (uniform)          0
## 10               %. of variables having complete cases 55.56% (5)
## 11   %. of variables having >0% and <50% missing cases 33.33% (3)
## 12 %. of variables having >=50% and <90% missing cases 11.11% (1)
## 13          %. of variables having >=90% missing cases     0% (0)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Structure of the data - Type = 2}
\KeywordTok{ExpData}\NormalTok{(}\DataTypeTok{data=}\NormalTok{df_total_sin_etiqueta,}\DataTypeTok{type=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Index Variable_Name Variable_Type Sample_n Missing_Count Per_of_Missing No_of_distinct_values
## 1     1        Pclass       integer     1309             0          0.000                     3
## 2     2           Sex     character     1309             0          0.000                     2
## 3     3           Age       numeric     1046           263          0.201                    98
## 4     4         SibSp       integer     1309             0          0.000                     7
## 5     5         Parch       integer     1309             0          0.000                     8
## 6     6         Cabin     character      295          1014          0.775                   187
## 7     7      Embarked     character     1307             2          0.002                     4
## 8     8  Count.ticket       integer     1309             0          0.000                     9
## 9     9    Unit.price       numeric     1308             1          0.001                   260
\end{verbatim}

Una vez que sabemos que tenemos valores nulos, cuántos tenemos y sabemos
las variables afectadas, se decide la estrategia para imputar dichos
valores

\textbf{Variable Cabin}:

Observamos que la variable ``Cabin'' tiene 1014 valores nulos de 1309,
por tanto, se decide eliminar dicha variable por la imposibilidad de
realizar una imputación generalizada.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Eliminamos variable Cabin}
\NormalTok{keep.cols <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Pclass"}\NormalTok{, }\StringTok{"Sex"}\NormalTok{, }\StringTok{"Age"}\NormalTok{, }\StringTok{"SibSp"}\NormalTok{, }\StringTok{"Parch"}\NormalTok{, }\StringTok{"Embarked"}\NormalTok{, }\StringTok{"Count.ticket"}\NormalTok{, }\StringTok{"Unit.price"}\NormalTok{)}
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[keep.cols]}
\end{Highlighting}
\end{Shaded}

\textbf{Variable Age}:

El número de registros de Age que son NA representan aproximadamente el
20\% de los registros totales.

Este dataset contiene variables categóricas y numéricas y para imputar
los valores nulos de la variable Age podemos usar el método
\texttt{kNN}. Aplicamos la función e imputamos los valores NA usando
todos los demás campos del dataset y con un valor de k igual a 3. El
algoritmo busca los registros de los 3 pasajeros más parecidos (cercanos
según la distancia Gower) al que contiene un valor nulo y usa los datos
de edades de estos pasajeros para imputar el valor faltante.

Una vez ejecutado el algoritmo para imputar los valores, volvemos a
comprobar si existen valores NA y podemos confirmar que todos los NA
para la variable edad han sido imputados.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Imputación de valores a los valores nulos de la variable age}
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\KeywordTok{kNN}\NormalTok{(df_total_sin_etiqueta, }\DataTypeTok{k=}\DecValTok{3}\NormalTok{)[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{]}
\KeywordTok{head}\NormalTok{(df_total_sin_etiqueta[}\KeywordTok{is.na}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Age),])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] Pclass       Sex          Age          SibSp        Parch        Embarked     Count.ticket Unit.price   Pclass_imp   Sex_imp     
## <0 rows> (or 0-length row.names)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[keep.cols]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Comprobacion de la no existencia de registros nulos para la variable age después de la imputación.}
\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Age))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\textbf{Variable Embarked}:

Se observa que la mayoría de las instancias pertenecen a la categoría S,
por tanto, las instancias con valores nulos en esta variable, las
imputaremos a S.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Exploración del resumen de los datos de la varibale Embarked }
\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Embarked <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Embarked)}
\KeywordTok{summary}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Embarked)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       C   Q   S 
##   2 270 123 914
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Imputación clase mayoritaria a variable Embarked }
\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Embarked[df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Embarked }\OperatorTok{==}\StringTok{ ""}\NormalTok{] <-}\StringTok{ "S"}
\KeywordTok{summary}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Embarked)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       C   Q   S 
##   0 270 123 916
\end{verbatim}

\textbf{Variable Unit.price}:

Actuaremos de igual forma que con la variable Age e imputaremos a través
del uso del kNN

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Imputación de valores a los valores nulos de la variable age}
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\KeywordTok{kNN}\NormalTok{(df_total_sin_etiqueta, }\DataTypeTok{k=}\DecValTok{3}\NormalTok{)[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{]}
\KeywordTok{head}\NormalTok{(df_total_sin_etiqueta[}\KeywordTok{is.na}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price),])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] Pclass       Sex          Age          SibSp        Parch        Embarked     Count.ticket Unit.price   Pclass_imp   Sex_imp     
## <0 rows> (or 0-length row.names)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[keep.cols]}
\end{Highlighting}
\end{Shaded}

\hypertarget{gestiuxf3n-de-los-valores-iguales-a-cero-en-el-dataset}{%
\subsubsection{\texorpdfstring{\textbf{Gestión de los valores iguales a
``cero'' en el
dataset}:}{Gestión de los valores iguales a ``cero'' en el dataset:}}\label{gestiuxf3n-de-los-valores-iguales-a-cero-en-el-dataset}}

Ahora comprobamos las variables que toman valores igual a cero sin que
tenga sentido que tomen este tipo de valor.

La variable que representa la ``clase'' toma valores iguales a cero y
consideramos que es correcto, lo mismo ocurre con las variables SibSp,
Parch, donde consideramos normal que existan valores iguales a cero,
significa que los pasajeros viajaban solos.

En cambio, los valores iguales a cero para la variable Unit.price son
algo más extraños. Entre los pasajeros que tienen un Unit.price igual a
cero hay personas que viajaban en primera, segunda y tecera clase.

La idea que un ticket sea gratuito no sería posible, por tanto,
volveremos a aplicar el método kNN para imputar estos valores.

Primero cambiaremos el valor de cero a NA y después actuaremos como en
el apartado anterior.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price[df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price }\OperatorTok{==}\StringTok{ "0"}\NormalTok{] <-}\StringTok{ }\OtherTok{NA}

\CommentTok{# Imputación de valores a los valores ceros de la variable Unit.price}
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\KeywordTok{kNN}\NormalTok{(df_total_sin_etiqueta, }\DataTypeTok{k=}\DecValTok{3}\NormalTok{)[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{]}
\KeywordTok{head}\NormalTok{(df_total_sin_etiqueta[}\KeywordTok{is.na}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price),])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] Pclass       Sex          Age          SibSp        Parch        Embarked     Count.ticket Unit.price   Pclass_imp   Sex_imp     
## <0 rows> (or 0-length row.names)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_total_sin_etiqueta <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[keep.cols]}

\CommentTok{# Comprobacion de la no existencia de registros ceros para la variable Unit.price después de la imputación.}
\KeywordTok{sum}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\textbf{Valores extremos}

No hemos encontrado valores que estén fuera de un rango razonable. Las
comprobaciones las hemos hecho anteriormente con
\texttt{sapply(df,\ summary)}.

Volvemos a visualizar boxplots para las variables numéricas que tenemos:
Age y Fare.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{oldpar =}\StringTok{ }\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{mar=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}

\CommentTok{# Boxplot variable Age}
\KeywordTok{boxplot}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{main=}\StringTok{"Boxplot Variable Age"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"Edad (años)"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\StringTok{"Boxplot Stats Variable Age}\CharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Boxplot Stats Variable Age\n"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot.stats}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{coef =} \FloatTok{1.5}\NormalTok{, }\DataTypeTok{do.conf =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{do.out =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stats
## [1]  0.17 21.00 27.00 37.00 61.00
## 
## $n
## [1] 1309
## 
## $conf
## [1] 26.30127 27.69873
## 
## $out
##  [1] 66.0 65.0 71.0 65.0 70.5 62.0 63.0 65.0 64.0 65.0 63.0 71.0 64.0 62.0 62.0 80.0 65.0 70.0 70.0 62.0 74.0 62.0 63.0 67.0 65.0 76.0 63.0 64.0 64.0 64.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Boxplot variable Age}
\KeywordTok{boxplot}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price, }\DataTypeTok{main=}\StringTok{"Boxplot Variable Unit.price"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"Precio billete unitario"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\StringTok{"Boxplot Stats Variable Fare}\CharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Boxplot Stats Variable Fare\n"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot.stats}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price, }\DataTypeTok{coef =} \FloatTok{1.5}\NormalTok{, }\DataTypeTok{do.conf =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{do.out =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stats
## [1]  3.1708  7.7208  8.3000 15.0500 26.0000
## 
## $n
## [1] 1309
## 
## $conf
## [1] 7.979931 8.620069
## 
## $out
##   [1]  35.64165  26.55000  26.55000  35.50000  43.83333  27.72080  48.84027  41.08540  30.98960  35.50000  40.00000  41.73750  27.72080  43.83333  30.58750  34.65420  31.67915  38.64375  82.50693  38.64375  26.28330  26.55000  39.60000  33.30000  30.68960  27.50000  33.50000  30.69580  28.71250  50.00000  26.55000  27.72080  48.84027  31.00000  37.75833  38.14585  45.00000  41.73750  30.00000  26.27710  26.55000  39.60000  28.83333 128.08230  26.55000  51.15417  33.90832  29.70000  26.28333
##  [50]  45.53960  27.72080  30.50000  82.50693  27.72083  36.30000  28.46460  27.71943  37.48214  41.21668  26.90000  33.90832  28.98960  28.50000  51.15417  66.82500  33.30000  26.90000  35.50000  43.83333  35.00000  27.50000  37.62500  34.65000  27.72085  33.90832  41.08540  42.30000  45.50500  30.00000  37.75833  30.00000  26.55000  27.95000  30.00000  43.83333  27.28610  26.55000  30.50000  27.75000  44.55210  26.55000  26.55000  38.50000  26.55000  45.53960  45.00000  29.70000  30.50000
##  [99]  49.50420  39.13335  28.83333  36.30000  26.55000  26.28750  29.70000  34.02080  28.98960  55.44480  26.55000  35.47500  49.50000  35.50000  35.47500  27.72083  26.55000  39.60000  45.50500  26.55000  26.38750  27.95000  27.72083  40.12500  26.55000  39.60000  39.13335  28.46460  26.55000  30.50000  51.15417  26.27710  32.32080  30.00000  30.50000  34.65000  35.50000  37.75833  66.82500 128.08230  52.83438  28.50000  26.55000  27.72083  45.50500  26.28750  26.28750  49.50420  26.55000
## [148]  45.50500  26.55000  52.83438 128.08230  30.00000  26.28333  37.48214  35.50000  26.55000  28.83333  30.00000  39.60000  52.83438  28.50000  30.00000  39.60000  30.69580  30.00000  31.68330  26.55000  26.55000  31.68330  40.00000  27.71943  29.70000  44.55210  41.21668  26.55000  50.49580  26.27710  27.71943  30.00000  30.00000  41.13335  30.58750  29.70000  31.68330  30.68960  37.48214  30.98960  30.50000  28.87500  26.55000  26.27710  29.70000  38.14585  30.00000  43.83333  37.48214
## [197]  37.48214  28.53750  43.83333  27.72080  42.30000  42.30000  55.44480  26.28333  27.72085  31.67920  55.44480  37.62085  28.87500  28.50000  37.48214  26.55000  26.55000  27.71943  55.44480  26.55000  50.49580  27.72080  27.72085  27.71943  27.71943  26.55000  82.50693  26.90000  45.50500  27.72080  42.50000  41.21668  42.30000  27.44580  26.55000  35.64165  37.62500  35.47500  27.72080  26.90000  68.38960  37.62085  68.38960  41.13335  39.60000  27.28610  45.50000  26.55000  33.90832
## [246]  48.84027  26.55000  52.83438  39.60000  29.70000 128.08230  31.67915  27.72085  29.70000  26.90000  27.28610  37.48214  50.00000  30.00000  39.60000  41.21668  29.70000  27.72080  42.30000  30.00000  36.30000
\end{verbatim}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-18-1} \end{center}

El boxplot muestra que hay outliers en estas dos variables. La mayoría
de los pasajeros eran jóvenes, aunque también encontramos pasajeros de
más de 65 años. En cuanto a la variable Unit.price, se comprueba que a
medida que el precio sube, la clase va bajando de 3 a 2 y de 2 a 1, con
lo cual no hay razón porqué pensar que los precios no son reales. En la
tabla siguiente podemos visualizar algunos de los pasajeros que pagaron
un precio de billete alto. Notamos que todos son de primera clase.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Muestra de varios precios de billetes unitarios en el rango alto}
\KeywordTok{tail}\NormalTok{(df_total_sin_etiqueta[df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price}\OperatorTok{>}\DecValTok{30}\NormalTok{,], }\DecValTok{15}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Pclass    Sex Age SibSp Parch Embarked Count.ticket Unit.price
## 1179      1   male  24     1     0        S            2   41.13335
## 1182      1   male  44     0     0        S            1   39.60000
## 1190      1   male  30     0     0        S            1   45.50000
## 1206      1 female  55     0     0        C            4   33.90832
## 1208      1   male  57     1     0        C            3   48.84027
## 1216      1 female  39     0     0        S            4   52.83438
## 1219      1   male  46     0     0        C            2   39.60000
## 1235      1 female  58     0     1        C            4  128.08230
## 1242      1 female  45     0     1        C            2   31.67915
## 1267      1 female  45     0     0        C            7   37.48214
## 1270      1   male  55     0     0        S            1   50.00000
## 1289      1 female  48     1     1        C            2   39.60000
## 1292      1 female  30     0     0        S            4   41.21668
## 1299      1   male  50     1     1        C            5   42.30000
## 1306      1 female  39     0     0        C            3   36.30000
\end{verbatim}

Aunque se acepte que los precios son reales, es cierto que hay uno que
es extremadamente alto y, aunque cierto, podría desvirtuar posibles
futuras predicciones, por tanto se estima que se podría cambiar por la
media de Unit.price agrupado por la primera clase, para tener un valor
imputado más real.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Imputación del valor máximo de Unit.price}
\NormalTok{df_price_Pclass <-}\StringTok{ }\KeywordTok{aggregate}\NormalTok{( df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price }\OperatorTok{~}\StringTok{ }\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Pclass, df_total_sin_etiqueta, mean )}
\NormalTok{mean_Unit.price <-}\StringTok{ }\NormalTok{df_price_Pclass[}\DecValTok{2}\NormalTok{][[}\DecValTok{1}\NormalTok{]][}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Muestra de varios precios de billetes unitarios en el rango alto}
\NormalTok{max_Unit.price <-}\StringTok{ }\KeywordTok{max}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price)}
\NormalTok{max_Unit.price}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 128.0823
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price[df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price }\OperatorTok{==}\StringTok{ }\NormalTok{max_Unit.price] <-}\StringTok{ }\NormalTok{mean_Unit.price}
\NormalTok{mean_Unit.price}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 34.50998
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{oldpar =}\StringTok{ }\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{mar=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}

\CommentTok{# Boxplot variable Age}
\KeywordTok{boxplot}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{main=}\StringTok{"Boxplot Variable Age"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"Edad (años)"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\StringTok{"Boxplot Stats Variable Age}\CharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Boxplot Stats Variable Age\n"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot.stats}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{coef =} \FloatTok{1.5}\NormalTok{, }\DataTypeTok{do.conf =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{do.out =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stats
## [1]  0.17 21.00 27.00 37.00 61.00
## 
## $n
## [1] 1309
## 
## $conf
## [1] 26.30127 27.69873
## 
## $out
##  [1] 66.0 65.0 71.0 65.0 70.5 62.0 63.0 65.0 64.0 65.0 63.0 71.0 64.0 62.0 62.0 80.0 65.0 70.0 70.0 62.0 74.0 62.0 63.0 67.0 65.0 76.0 63.0 64.0 64.0 64.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Boxplot variable Age}
\KeywordTok{boxplot}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price, }\DataTypeTok{main=}\StringTok{"Boxplot Variable Unit.price"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"Precio billete unitario"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(}\StringTok{"Boxplot Stats Variable Fare}\CharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Boxplot Stats Variable Fare\n"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot.stats}\NormalTok{(df_total_sin_etiqueta}\OperatorTok{$}\NormalTok{Unit.price, }\DataTypeTok{coef =} \FloatTok{1.5}\NormalTok{, }\DataTypeTok{do.conf =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{do.out =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $stats
## [1]  3.1708  7.7208  8.3000 15.0500 26.0000
## 
## $n
## [1] 1309
## 
## $conf
## [1] 7.979931 8.620069
## 
## $out
##   [1] 35.64165 26.55000 26.55000 35.50000 43.83333 27.72080 48.84027 41.08540 30.98960 35.50000 40.00000 41.73750 27.72080 43.83333 30.58750 34.65420 31.67915 38.64375 82.50693 38.64375 26.28330 26.55000 39.60000 33.30000 30.68960 27.50000 33.50000 30.69580 28.71250 50.00000 26.55000 27.72080 48.84027 31.00000 37.75833 38.14585 45.00000 41.73750 30.00000 26.27710 26.55000 39.60000 28.83333 34.50998 26.55000 51.15417 33.90832 29.70000 26.28333 45.53960 27.72080 30.50000 82.50693 27.72083 36.30000
##  [56] 28.46460 27.71943 37.48214 41.21668 26.90000 33.90832 28.98960 28.50000 51.15417 66.82500 33.30000 26.90000 35.50000 43.83333 35.00000 27.50000 37.62500 34.65000 27.72085 33.90832 41.08540 42.30000 45.50500 30.00000 37.75833 30.00000 26.55000 27.95000 30.00000 43.83333 27.28610 26.55000 30.50000 27.75000 44.55210 26.55000 26.55000 38.50000 26.55000 45.53960 45.00000 29.70000 30.50000 49.50420 39.13335 28.83333 36.30000 26.55000 26.28750 29.70000 34.02080 28.98960 55.44480 26.55000 35.47500
## [111] 49.50000 35.50000 35.47500 27.72083 26.55000 39.60000 45.50500 26.55000 26.38750 27.95000 27.72083 40.12500 26.55000 39.60000 39.13335 28.46460 26.55000 30.50000 51.15417 26.27710 32.32080 30.00000 30.50000 34.65000 35.50000 37.75833 66.82500 34.50998 52.83438 28.50000 26.55000 27.72083 45.50500 26.28750 26.28750 49.50420 26.55000 45.50500 26.55000 52.83438 34.50998 30.00000 26.28333 37.48214 35.50000 26.55000 28.83333 30.00000 39.60000 52.83438 28.50000 30.00000 39.60000 30.69580 30.00000
## [166] 31.68330 26.55000 26.55000 31.68330 40.00000 27.71943 29.70000 44.55210 41.21668 26.55000 50.49580 26.27710 27.71943 30.00000 30.00000 41.13335 30.58750 29.70000 31.68330 30.68960 37.48214 30.98960 30.50000 28.87500 26.55000 26.27710 29.70000 38.14585 30.00000 43.83333 37.48214 37.48214 28.53750 43.83333 27.72080 42.30000 42.30000 55.44480 26.28333 27.72085 31.67920 55.44480 37.62085 28.87500 28.50000 37.48214 26.55000 26.55000 27.71943 55.44480 26.55000 50.49580 27.72080 27.72085 27.71943
## [221] 27.71943 26.55000 82.50693 26.90000 45.50500 27.72080 42.50000 41.21668 42.30000 27.44580 26.55000 35.64165 37.62500 35.47500 27.72080 26.90000 68.38960 37.62085 68.38960 41.13335 39.60000 27.28610 45.50000 26.55000 33.90832 48.84027 26.55000 52.83438 39.60000 29.70000 34.50998 31.67915 27.72085 29.70000 26.90000 27.28610 37.48214 50.00000 30.00000 39.60000 41.21668 29.70000 27.72080 42.30000 30.00000 36.30000
\end{verbatim}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-22-1} \end{center}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{anuxe1lisis-de-datos}{%
\section{\texorpdfstring{\textbf{Análisis de
datos}}{Análisis de datos}}\label{anuxe1lisis-de-datos}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Una vez limpiado el archivo que contenía las líneas de los conjuntos
train y test, deberemos separar otra vez los conjuntos ya que únicamente
tenemos datos de la etiqueta para el conjunto de entrenamiento.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Guardamos en disco el archivo global}
\KeywordTok{write.csv}\NormalTok{(df_total_sin_etiqueta, }\StringTok{"Titanic_global_sin_etiqueta.csv"}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creación del conjunto de train y test después de la limpieza del dataset}
\NormalTok{train <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[}\DecValTok{1}\OperatorTok{:}\NormalTok{train_rows, ]}
\NormalTok{test <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[(train_rows }\OperatorTok{+}\StringTok{ }\DecValTok{1}\NormalTok{)}\OperatorTok{:}\NormalTok{(train_rows}\OperatorTok{+}\NormalTok{test_rows), ]}
\end{Highlighting}
\end{Shaded}

Y añadimos las etiquetas al conjunto de train:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Adición de las etiquetas al conjunto de entrenamiento}
\NormalTok{train <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(train, etiquetas )}
\end{Highlighting}
\end{Shaded}

Guardamos en disco los archivos train y test procesados y ``limpios''
preparados para su posterior análisis.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Guardamos en disco los archivos procesados}
\KeywordTok{write.csv}\NormalTok{(train, }\StringTok{"train_processed.csv"}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{)}
\KeywordTok{write.csv}\NormalTok{(test, }\StringTok{"test_processed.csv"}\NormalTok{, }\DataTypeTok{row.names =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\textbf{Screening}

Antes de crear las visualizaciones determinamos que las variables
numéricas son: Age y Unit.price que corresponden a la edad de los
pasajeros y el precio unitario del billete.

\textbf{OLGA: revisar aquí, si las variables son categóricas o no,
parece que nos va mejor que no lo sean} Survived, Sex, Embarked son
variables categóricas y Pclass, SibSp, Parch son variables categóricas
ordinales (existen rangos en los valores de las variables).

Realizamos las transformaciones oportunas para guardar las variables con
sus tipos correspondientes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Categóricas}
\NormalTok{train}\OperatorTok{$}\NormalTok{Survived <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(train}\OperatorTok{$}\NormalTok{Survived)}
\NormalTok{train}\OperatorTok{$}\NormalTok{Sex <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(train}\OperatorTok{$}\NormalTok{Sex)}

\CommentTok{# Categóricas ordinales}
\CommentTok{#train$Pclass <- factor(train$Pclass, levels= c(1, 2, 3))}
\CommentTok{#train$SibSp <- factor(train$SibSp, levels = c(0, 1, 2, 3, 4, 5, 8))}
\CommentTok{#train$Parch <- factor(train$Parch, levels = c(0, 1, 2, 3, 4, 5, 6, 9))}
\end{Highlighting}
\end{Shaded}

Creamos una función que nos facilite visualizar las distribuciones de
las variables, así como detectar posibles valores extremos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{visualiz <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(data, colm, facet.colm, title, }\DataTypeTok{facetPlot=}\OtherTok{FALSE}\NormalTok{)\{}
\NormalTok{oldpar =}\StringTok{ }\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{mar=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{truehist}\NormalTok{(data[[colm]], }\DataTypeTok{main =}\NormalTok{ title)}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{v =} \KeywordTok{mean}\NormalTok{(data[[colm]]), }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{3}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{);}
\KeywordTok{abline}\NormalTok{(}\DataTypeTok{v =} \KeywordTok{median}\NormalTok{(data[[colm]]), }\DataTypeTok{lwd=}\DecValTok{3}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{, }\DataTypeTok{col=}\StringTok{"blue"}\NormalTok{);}
\KeywordTok{qqnorm}\NormalTok{(data[[colm]], }\DataTypeTok{main =}\NormalTok{ title);}\KeywordTok{qqline}\NormalTok{(data[[colm]], }\DataTypeTok{col =} \DecValTok{2}\NormalTok{ )}
\ControlFlowTok{if}\NormalTok{ (facetPlot}\OperatorTok{==}\OtherTok{TRUE}\NormalTok{) \{}
  \KeywordTok{boxplot}\NormalTok{(data[[colm]]}\OperatorTok{~}\NormalTok{data[[facet.colm]], }\DataTypeTok{main =} \KeywordTok{paste}\NormalTok{(}\StringTok{"Survived by"}\NormalTok{, title))}
\NormalTok{\}}

\KeywordTok{boxplot}\NormalTok{(data[[colm]], }\DataTypeTok{main =}\NormalTok{ title)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{Visualización de las variables numéricas}

Los pasajeros que tienen edades entre los cuantiles 25 y 75 tienen entre
20 y 40 años. La edad mediana para los pasajeros que sobrevivieron y los
que no es muy similar.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{visualiz}\NormalTok{(train, }\StringTok{"Age"}\NormalTok{, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Age"}\NormalTok{, }\DataTypeTok{facetPlot=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-29-1} \end{center}

Si vemos la variable Unit.price (precio unitario del billete), la
mayoría de los pasajeros pagaron muy poco por el billete. Aquí en el
boxplot encontramos outliers pero consideramos que no deberíamos
descartar estas entradas ya que hay pocos pasajeros que pagaron un
importe alto por el billete y esta información puede ser muy interesante
para predecir la posibilidad de supervivencia: ¿Viajar en una clase
privilegiada aumenta la posibilidad de sobrevivir?

En el boxplot además podemos ver que las personas que sobreviven tienen
una mediana más alta en el precio del billete.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{visualiz}\NormalTok{(train, }\StringTok{"Unit.price"}\NormalTok{, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Unit.price"}\NormalTok{, }\DataTypeTok{facetPlot=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-30-1} \end{center}

A continuación visualizamos los datos para las variables Class, Sex,
Siblings/Spouse, Parents/Children

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{oldpar =}\StringTok{ }\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{), }\DataTypeTok{mar=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}

\KeywordTok{plot}\NormalTok{(}\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Pclass, train}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{), }\DataTypeTok{main=}\StringTok{"Class"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(}\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Sex, train}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{), }\DataTypeTok{main=}\StringTok{"Sex"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(}\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{SibSp, train}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{), }\DataTypeTok{main=}\StringTok{"Siblings/Spouse"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(}\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Parch, train}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{), }\DataTypeTok{main=}\StringTok{"Parents/Children"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(}\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Embarked, train}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{), }\DataTypeTok{main=}\StringTok{"Embarked"}\NormalTok{)}

\KeywordTok{plot}\NormalTok{(}\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Count.ticket, train}\OperatorTok{$}\NormalTok{Survived), }\DataTypeTok{col =} \KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{), }\DataTypeTok{main=}\StringTok{"Embarked"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-31-1} \end{center}

Las personas que viajaban en tercera clase tienen la menor proporción de
supervivencia comparando con las personas que viajaban en primera clase.
Las mujeres que viajaban en el titanic sobrevivieron en su mayoría. Los
hombres sobrevivieron en mucho menor proporción.

La mayoría de personas viajaba sin familiares (hermanos, pareja, padres
o hijos) y parece ser que el porcentaje de supervivencia es algo más
alto en personas que tenían familiares a bordo.

La mayoría de personas embarcaron en el punto S, pero el mayor
porcentaje de supervivencia lo tienen las personas que embarcaron en C.

Los pasajeros que viajaban varias personas con el mismo billete también
tienen una mayor supervivencia ( hasta 4 pasajeros ). 1 o más de 4
pasajeros con el mismo billete tienen la misma proporción de
supervivencia.

\textbf{Análisis bivariable}

Vamos a visualizar algunos plots que nos permiten ver la supervivencia
de pasajeros combinando dos variables.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{grid.newpage}\NormalTok{()}

\NormalTok{sex.class <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{train, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Sex, }\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{position =} \StringTok{'fill'}\NormalTok{)}\OperatorTok{+}\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Pclass)}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{))}
\NormalTok{sibs.class <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{train, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{SibSp, }\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{position =} \StringTok{'fill'}\NormalTok{)}\OperatorTok{+}\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Pclass)}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{))}
\NormalTok{parch.class <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{train, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Parch, }\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{position =} \StringTok{'fill'}\NormalTok{)}\OperatorTok{+}\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Pclass)}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{))}
\NormalTok{embark.class <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{train, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Embarked, }\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{position =} \StringTok{'fill'}\NormalTok{)}\OperatorTok{+}\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Pclass)}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{))}

\KeywordTok{grid.arrange}\NormalTok{(sex.class, sibs.class, parch.class, embark.class,  }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-32-1} \end{center}

Las mujeres que viajaban en primera y segunda clase sobrevivieron casi
todas. Los hombres sobrevivieron en mucho menor medida, incluso los
hombres que viajaron en primera clase.

Las personas que viajaban con hermanos o pareja en primera clase
sobrevivieron en mayor medida que las personas que viajaron solas. En
primera y segunda clase no hay personas que viajasen con más de 3
hermanos. En tercera clase hay personas que viajaron con hasta 8
hermanos en este caso un menor número de hermanos (excepto cero) parece
indicar una mayor supervivencia.

También hemos visualizado la supervivencia en función del lugar donde
los pasajeros embarcaron en el Titanic. Los pasajeros de tercera clase
que embarcaron en el punto S han tenido menos proporción de
supervivencia que los demás. Los pasajeros de segunda clase que
embarcaron en Q sobrevivieron en mayor proporción que los pasajeros de
segunda clase que embarcaron en otros puntos. Para los pasajeros de
primera clase el punto de embarque con mayor porcentaje de
superviviencia es C.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{train, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Sex, }\DataTypeTok{fill=}\KeywordTok{as.factor}\NormalTok{(Pclass)))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{position =} \StringTok{'fill'}\NormalTok{)}\OperatorTok{+}\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Embarked)}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{, }\StringTok{"red"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-33-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{train, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Embarked, }\DataTypeTok{fill=}\KeywordTok{as.factor}\NormalTok{(Survived)))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{position =} \StringTok{'fill'}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{, }\StringTok{"red"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-34-1} \end{center}

Visualizamos la supervivencia usando las variables de la clase en la que
viaja el pasajero y el número de personas que viajan con el mismo
billete.

En el Titanic viajaron familias enteras de hasta 7 personas en primera
clase y incluso de 11 personas en tercera clase. La supervivencia de
personas que viajaban sobre el mismo billete en tercera clase es
comparable con el mismo dato en segunda clase.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{train, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Count.ticket, }\DataTypeTok{fill=}\NormalTok{Survived))}\OperatorTok{+}\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{position =} \StringTok{'fill'}\NormalTok{)}\OperatorTok{+}\KeywordTok{facet_wrap}\NormalTok{(}\OperatorTok{~}\NormalTok{Pclass)}\OperatorTok{+}\StringTok{ }\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\KeywordTok{c}\NormalTok{(}\StringTok{"black"}\NormalTok{, }\StringTok{"orange"}\NormalTok{, }\StringTok{"red"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-35-1} \end{center}

\hypertarget{anuxe1lisis-de-los-datos.}{%
\subsection{Análisis de los datos.}\label{anuxe1lisis-de-los-datos.}}

\hypertarget{selecciuxf3n-de-los-grupos-de-datos-que-se-quieren-analizarcomparar-planificaciuxf3n-de-los-anuxe1lisis-a-aplicar.}{%
\subsubsection{Selección de los grupos de datos que se quieren
analizar/comparar (planificación de los análisis a
aplicar).}\label{selecciuxf3n-de-los-grupos-de-datos-que-se-quieren-analizarcomparar-planificaciuxf3n-de-los-anuxe1lisis-a-aplicar.}}

La pregunta que planteamos inicialmente es si entre las variables que
tenemos en el dataset existen algunas que influyen en mayor medida en la
supervivencia de los pasajeros del Titanic. En los análisis anteriores
hemos comprobado visualmente que las personas de primera clase han
sobrevivido en mayor medida, que las mujeres y los niños tienen una
mayor proporción de supervivencia. También hemos visto que personas que
viajan acompañadas, ya sea por familia o amigos, tiene una proporcion de
supervivencia algo mejor.

Vamos a usar estos datos para analizar el dataset en mayor profundidad.
Para ello necesitamos datasets especializados.

\textbf{CARLOS: NO VEO PQ NO HACEMOS UN GRUPO CON LA PCLASS 3}
\textbf{Olga: NO hay pomivo por el que no hacer class3, pero pensaba que
nos ibamos a centrar en con cuantos viajan y dejar lo demás de lado.. no
sé }

OLGA: Si seguimos con lo que hemos hablado, de centrarnos en si los
pasajeros viajan solos o no, debemos separar estos 3 pares de
datasets.\textbf{las variables sibsp, parch están como factor, voy a
comentar la parte donde se les transforma en factor..}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Dataframe por pasajeros que viajaban solos o acompañados}
\NormalTok{train.single <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Count.ticket}\OperatorTok{==}\StringTok{"1"}\NormalTok{,]}
\NormalTok{train.many <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Count.ticket}\OperatorTok{>}\DecValTok{1}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Dataframe por pasajeros que viajaban solos o acompañados}
\NormalTok{train.spouse <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{SibSp}\OperatorTok{>}\DecValTok{0}\NormalTok{,]}
\NormalTok{train.not.spouse <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{sibsp}\OperatorTok{==}\DecValTok{0}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Dataframe por pasajeros que viajaban solos o acompañados}
\NormalTok{train.children <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Parch}\OperatorTok{>}\DecValTok{10}\NormalTok{,]}
\NormalTok{train.no.children <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Parch}\OperatorTok{==}\DecValTok{0}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Dataframes por clase de pasajero}
\NormalTok{train.first <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Pclass}\OperatorTok{==}\DecValTok{1}\NormalTok{,]}
\NormalTok{train.second <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Pclass}\OperatorTok{==}\DecValTok{2}\NormalTok{,]}
\NormalTok{train.first.second <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Pclass}\OperatorTok{==}\DecValTok{1} \OperatorTok{|}\StringTok{ }\NormalTok{train}\OperatorTok{$}\NormalTok{Pclass}\OperatorTok{==}\DecValTok{2}\NormalTok{,]}
\NormalTok{train.first.second}\OperatorTok{$}\NormalTok{Pclass <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(train.first.second}\OperatorTok{$}\NormalTok{Pclass, }\DataTypeTok{levels =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Dataframe por sexo del pasajero}
\NormalTok{train.male <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Sex}\OperatorTok{==}\StringTok{"male"}\NormalTok{, ]}
\NormalTok{train.female <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Sex}\OperatorTok{==}\StringTok{"female"}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Dataframe por edad del pasajero}
\NormalTok{train.young <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Age}\OperatorTok{<}\DecValTok{18}\NormalTok{,]}
\NormalTok{train.older <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Age}\OperatorTok{>=}\DecValTok{18}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train.survived <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Survived}\OperatorTok{==}\DecValTok{1}\NormalTok{,]}
\NormalTok{train.not.survived <-}\StringTok{ }\NormalTok{train[train}\OperatorTok{$}\NormalTok{Survived}\OperatorTok{==}\DecValTok{0}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\hypertarget{comprobaciuxf3n-de-la-normalidad-y-homogeneidad-de-la-varianza.}{%
\subsubsection{Comprobación de la normalidad y homogeneidad de la
varianza.}\label{comprobaciuxf3n-de-la-normalidad-y-homogeneidad-de-la-varianza.}}

\textbf{Normalidad}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ visualiz1 <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(D1, D2, name1, name2, title)\{}
\NormalTok{   oldpar =}\StringTok{ }\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{mar=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
  \KeywordTok{truehist}\NormalTok{(D1, }\DataTypeTok{main =} \KeywordTok{paste}\NormalTok{(name1,}\StringTok{" "}\NormalTok{, title))}
  \KeywordTok{abline}\NormalTok{(}\DataTypeTok{v =} \KeywordTok{mean}\NormalTok{(D1), }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{3}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{);}
  \KeywordTok{abline}\NormalTok{(}\DataTypeTok{v =} \KeywordTok{median}\NormalTok{(D1), }\DataTypeTok{lwd=}\DecValTok{3}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{, }\DataTypeTok{col=}\StringTok{"blue"}\NormalTok{);}
  \KeywordTok{qqnorm}\NormalTok{(D1, }\DataTypeTok{main =} \KeywordTok{paste}\NormalTok{(name1, }\StringTok{" "}\NormalTok{, title));}\KeywordTok{qqline}\NormalTok{(D1, }\DataTypeTok{col =} \DecValTok{2}\NormalTok{ )}
  \KeywordTok{truehist}\NormalTok{(D2, }\DataTypeTok{main =} \KeywordTok{paste}\NormalTok{(name2,}\StringTok{" "}\NormalTok{, title))}
  \KeywordTok{abline}\NormalTok{(}\DataTypeTok{v =} \KeywordTok{mean}\NormalTok{(D2), }\DataTypeTok{col=}\StringTok{"red"}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{3}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{);}
  \KeywordTok{abline}\NormalTok{(}\DataTypeTok{v =} \KeywordTok{median}\NormalTok{(D2), }\DataTypeTok{lwd=}\DecValTok{3}\NormalTok{, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{, }\DataTypeTok{col=}\StringTok{"blue"}\NormalTok{);}
  \KeywordTok{qqnorm}\NormalTok{(D2, }\DataTypeTok{main =} \KeywordTok{paste}\NormalTok{(name2,}\StringTok{" "}\NormalTok{, title)); }\KeywordTok{qqline}\NormalTok{(D2, }\DataTypeTok{col =} \DecValTok{2}\NormalTok{ )}

\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{Variable age}

Visualizamos los datos de la edad para personas que sobrevivieron en el
hundimiento frente a personas que no sobrevivieron.

La media y la mediana de los pasajeros que sobrevivieron están muy
cerca. Las personas que no sobrevivieron tienen una edad mediana más
baja que la edad media. Los valores de estos dos indicadores de
tendencia central son más altos para personas que no sobrevivieron: las
personas que muerieron tenían una media de edad algo más alta que los
que sobrevivieron.

Según el qqplot las dos distribuciones son cercanas a la normal. Según
el teorema del límite central podemos asumir la distribución normal de
la media de estas dos muestras ya que sus tamaños son mayores que 30
observaciones.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{visualiz1}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Age, train.not.survived}\OperatorTok{$}\NormalTok{Age, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Not Survived"}\NormalTok{, }\StringTok{""}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-44-1} \end{center}

Comprobaremos de la igualdad de las varianzas entre los conjuntos de
datos de pasajeros que sobrevivieron y no. Para ello usamos la función
\texttt{var.test}.

El contraste de varianzas se realiza mediante un contraste de hipótesis,
donde aceptar H0 significaría que las varianzas son iguales.

El valor p-value que obtenemos es de 0.15. Este valor indica que
rechazando la hipótesis nula de igualdad de varianzas probablemente
estaríamos comentiendo un error. Las varianzas en la edad de los
pasajeros que sobrevivieron y los que no sobrevivieron son iguales y
podemos hacer esta afirmación con un nivel de confianza del 95\%.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var.test}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Age, train.not.survived}\OperatorTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  train.survived$Age and train.not.survived$Age
## F = 1.1489, num df = 341, denom df = 548, p-value = 0.1508
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.9507576 1.3943200
## sample estimates:
## ratio of variances 
##           1.148887
\end{verbatim}

\textbf{Variable Unit price: precio del billete unitario}

Visualizamos el precio del billete unitario para los pasajeros que
sobrevivieron frente a los que no. Podemos ver que la media y la mediana
del precio de billete para los pasajeros que sobrevivieron están
bastante separadas. El precio que corresponde a la mediana es alrededor
de 13 y la media es más cercana a 20. Existe esta diferencia porque la
distribución tiene una cola larga a la derecha, tenemos pasajeros que
pagaron un precio muy alto por sus billetes.

La mayoría de los pasajeros que no sobrevivieron pagaron un precio bajo
por el billete, hay pocas personas que pagaron precios más altos y no
sobrevivieron.

Ninguna de las dos distribuciones es normal, aunque para el fin de hacer
un contraste de hipótesos sobre la media podemos asumir que la media
poblacional se distribuye normalmente (teorema del límite central).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{visualiz1}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Unit.price, train.not.survived}\OperatorTok{$}\NormalTok{Unit.price, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Not Survived"}\NormalTok{, }\StringTok{"Unit price"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-46-1} \end{center}

Realizamos el test de igualdad de las varianzas para el precio del
billete para pasajeros que sobrevivieron frente a los que no
sobrevivieron. El valor p nos indica que podemos rechazar H0, es decir,
las varianzas entre estos dos grupos de pasajeros son diferentes.

En los histogramas podemos ver que los pasajeros que sobrevivieron de
media pagaron más por sus billetes. Tanto en el grupo de supervivientes
como de no supervivientes la media es mayor que la mediana, dado que
tenemos outliers de precio de billete unitario muy alto.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var.test}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Unit.price, train.not.survived}\OperatorTok{$}\NormalTok{Unit.price)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  train.survived$Unit.price and train.not.survived$Unit.price
## F = 2.0651, num df = 341, denom df = 548, p-value = 3.73e-14
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  1.708968 2.506262
## sample estimates:
## ratio of variances 
##           2.065101
\end{verbatim}

\textbf{Variable SibSp: pareja o hermanos}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{visualiz1}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{SibSp, train.not.survived}\OperatorTok{$}\NormalTok{SibSp, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Not Survived"}\NormalTok{, }\StringTok{"Siblings / Spouse"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-48-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var.test}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{SibSp, train.not.survived}\OperatorTok{$}\NormalTok{SibSp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  train.survived$SibSp and train.not.survived$SibSp
## F = 0.30256, num df = 341, denom df = 548, p-value < 2.2e-16
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.2503810 0.3671926
## sample estimates:
## ratio of variances 
##          0.3025581
\end{verbatim}

\textbf{Variable Parch: padres o hijos}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{visualiz1}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Parch, train.not.survived}\OperatorTok{$}\NormalTok{Parch, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Not Survived"}\NormalTok{, }\StringTok{"Parents/Children"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-50-1} \end{center}

El test de igualdad de las varianzas indica que no podemos rechazar la
hipótesis nula. Entre los grupos que sobrevivieron y los que no
sobrevivieron las varianzas de la variable Parch son iguales.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var.test}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Parch, train.not.survived}\OperatorTok{$}\NormalTok{Parch)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  train.survived$Parch and train.not.survived$Parch
## F = 0.87889, num df = 341, denom df = 548, p-value = 0.1908
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.7273246 1.0666475
## sample estimates:
## ratio of variances 
##          0.8788923
\end{verbatim}

\textbf{Variable Count.ticket: número de personas que viajaban con un
mismo billete}

Visualizamos un histograma que muestra la frecuencia de recuento de
billetes: pasajeros que viajaban solos hasta pasajeros que viajaban con
muchos acompañantes.

La media para el recuento de billetes es de 2 mientras que la mediana es
1.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{visualiz1}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Count.ticket, train.not.survived}\OperatorTok{$}\NormalTok{Count.ticket, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Not Survived"}\NormalTok{, }\StringTok{"Ticket count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-52-1} \end{center}

En este caso tenemos un valor p muy bajo y por lo tanto podemos aceptar
H1 que indica que las varianzas de la variable Count.ticket son
diferentes en el grupo de supervivientes y no supervivientes.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var.test}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Count.ticket, train.not.survived}\OperatorTok{$}\NormalTok{Count.ticket)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  train.survived$Count.ticket and train.not.survived$Count.ticket
## F = 0.55183, num df = 341, denom df = 548, p-value = 3.459e-09
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.4566685 0.6697206
## sample estimates:
## ratio of variances 
##          0.5518339
\end{verbatim}

\hypertarget{aplicaciuxf3n-de-pruebas-estaduxedsticas-para-comparar-los-grupos-de-datos.-en-funciuxf3n-de-los-datos-y-el-objetivo-del-estudio-aplicar-pruebas-de-contraste-de-hipuxf3tesis-correlaciones-regresiones-etc.-aplicar-al-menos-tres-muxe9todos-de-anuxe1lisis-diferentes.}{%
\subsubsection{Aplicación de pruebas estadísticas para comparar los
grupos de datos. En función de los datos y el objetivo del estudio,
aplicar pruebas de contraste de hipótesis, correlaciones, regresiones,
etc. Aplicar al menos tres métodos de análisis
diferentes.}\label{aplicaciuxf3n-de-pruebas-estaduxedsticas-para-comparar-los-grupos-de-datos.-en-funciuxf3n-de-los-datos-y-el-objetivo-del-estudio-aplicar-pruebas-de-contraste-de-hipuxf3tesis-correlaciones-regresiones-etc.-aplicar-al-menos-tres-muxe9todos-de-anuxe1lisis-diferentes.}}

\textbf{Contraste de hipótesis sobre el sexo y nivel de supervivencia}

¿La proporción de supervivencia en hombres es inferior a la de las
mujeres?

Acorde con la pregunta planteada, realizaremos un contraste de hipótesis
con las siguientes hipótesis de partida:

Hipótesis nula - H0: La proporción de hombres que sobreviven es igual o
mayor a 50\% -\textgreater{} H0: p \textgreater= p0, siendo p0 = 0.5\\
Hipótesis alternativa - H1: La proporción de hombres es menor a 50\%
-\textgreater{} H1: p \textless{} p0, siendo po = 0.5

Este contraste de hipótesis representa un test de la proporción de la
población por la cola izquierda, por tanto, el valor p0 representará,
bajo la hipótesis nula, el límite inferior de la supuesta verdadera
proporción de la población.\\
Este contraste rechazará la HO si el estadístico calculado es menor o
igual al valor crítico (con signo negativo) al nivel de significación
estimado.

El hecho que la proporción de hombres que sobreviven sea menor que 0.5,
implicaría que la proporción de hombres que sobreviven es inferior a la
de las mujeres.

Debido a que es un contraste de hipótesis sobre proporción de una
muestra, y esta muestra es considerada grande (n \textgreater{} 30),
podremos definir un estadístico de contraste como una observación de una
variable aleatoria que se distribuye aproximadamente como una N(0,1).

Debido al planteamiento de la hipótesis nula y su alternativa y por cómo
se han descrito las hipótesis H0 y H1, se observa que la hipótesis
alternativa es unilateral, puesto que se plantea como un límite a un
solo valor dado.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Fijamos un nivel de significación}

\NormalTok{alfa <-}\StringTok{ }\FloatTok{0.05}
\end{Highlighting}
\end{Shaded}

Determinamos el estadístico de contraste, en este caso, la muestra es
grande y proviene de una distribución de Bernoulli de parámetro p, con
lo cual, según el Teorema del Límite Central podremos utilizar el
estadístico de contraste mostrado anteriormente.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Determinación del estadístico de contraste}

\NormalTok{train.survived_M <-}\StringTok{ }\NormalTok{train.survived[train.survived}\OperatorTok{$}\NormalTok{Sex}\OperatorTok{==}\StringTok{"male"}\NormalTok{,]}
\NormalTok{train.survived_F <-}\StringTok{ }\NormalTok{train.survived[train.survived}\OperatorTok{$}\NormalTok{Sex}\OperatorTok{==}\StringTok{"female"}\NormalTok{,]}



\NormalTok{n_Sex <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Sex)}

\NormalTok{n_Sex_M <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived_M}\OperatorTok{$}\NormalTok{Sex)}

\NormalTok{n_Sex_F <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived_F}\OperatorTok{$}\NormalTok{Sex)}



\CommentTok{# Proporción muestral de hombres}
\NormalTok{p_hat <-}\StringTok{ }\NormalTok{n_Sex_M}\OperatorTok{/}\NormalTok{n_Sex}


\CommentTok{# Proporción hipotesis nula}
\NormalTok{p_}\DecValTok{0}\NormalTok{ <-}\StringTok{ }\FloatTok{0.5}


\CommentTok{# Estadístico empleado z_p}
\NormalTok{z_p =}\StringTok{ }\NormalTok{(p_hat }\OperatorTok{-}\StringTok{ }\NormalTok{p_}\DecValTok{0}\NormalTok{)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(p_}\DecValTok{0} \OperatorTok{*}\StringTok{ }\NormalTok{(}\DecValTok{1} \OperatorTok{-}\StringTok{ }\NormalTok{p_}\DecValTok{0}\NormalTok{)}\OperatorTok{/}\NormalTok{n_Sex) }

\CommentTok{# Cálculo de valores críticos para el valor de significación asignado}

\NormalTok{z_p.alfa =}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alfa) }


\CommentTok{# Cálculo del valor P en nuestro contraste de hipótesis}

\NormalTok{valor_p_Sex =}\StringTok{ }\KeywordTok{pnorm}\NormalTok{(z_p) }
 

\KeywordTok{data.frame}\NormalTok{(n_Sex, n_Sex_M, n_Sex_F, p_hat, p_}\DecValTok{0}\NormalTok{, z_p, }\OperatorTok{-}\NormalTok{z_p.alfa, valor_p_Sex)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   n_Sex n_Sex_M n_Sex_F     p_hat p_0       z_p X.z_p.alfa  valor_p_Sex
## 1   342     109     233 0.3187135 0.5 -6.705152  -1.644854 1.005984e-11
\end{verbatim}

Tal y como se ha planteado H0 y H1, siendo H1 p \textless{} 0.5,
rechazaremos H0 si el valor del estadístico z\_p es menor que el valor
crítico (en signo negativo), siendo este el caso -6.70 \textless{}
-1.64.

Según el estadístico de contraste utilizado y el valor crítico
calculado, al ser el primero (-6.70) menor que el segundo (-1.64), al
0.05 de nivel de significancia, podemos rechazar la hipótesis nula de
que la proporción de supervivencia en hombres es mayor o igual a 50\%
respecto al de las mujeres.

De igual forma, al ser valor p casi nulo y por tanto menor que nuestro
nivel de significación (0.05), el valor p es significativo y podemos
rechazar, confirmando el contraste anterior, la hipótesis nula.

Siguiendo la misma metodología, responderemos a las siguientes
preguntas:

\textbf{¿La proporción de supervivencia en menores es inferior a la de
los mayores?}

Hipótesis nula - H0: La proporción de menores que sobreviven es igual o
mayor a 50\% -\textgreater{} H0: p \textgreater= p0, siendo po = 0.5\\
Hipótesis alternativa - H1: La proporción de menores es menor a 50\%
-\textgreater{} H1: p \textless{} p0, siendo po = 0.5

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Determinación del estadístico de contraste}

\NormalTok{train.survived_Y <-}\StringTok{ }\NormalTok{train.survived[train.survived}\OperatorTok{$}\NormalTok{Age}\OperatorTok{<}\DecValTok{18}\NormalTok{,]}
\NormalTok{train.survived_O <-}\StringTok{ }\NormalTok{train.survived[train.survived}\OperatorTok{$}\NormalTok{Age}\OperatorTok{>=}\DecValTok{18}\NormalTok{,]}


\NormalTok{n_Age <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Age)}

\NormalTok{n_Age_Y <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived_Y}\OperatorTok{$}\NormalTok{Age)}

\NormalTok{n_Age_O <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived_O}\OperatorTok{$}\NormalTok{Age)}



\CommentTok{# Proporción muestral de menores}
\NormalTok{p_hat <-}\StringTok{ }\NormalTok{n_Age_Y}\OperatorTok{/}\NormalTok{n_Age}


\CommentTok{# Proporción hipotesis nula}
\NormalTok{p_}\DecValTok{0}\NormalTok{ <-}\StringTok{ }\FloatTok{0.5}

\CommentTok{# Estadístico empleado z_p}
\NormalTok{z_p =}\StringTok{ }\NormalTok{(p_hat }\OperatorTok{-}\StringTok{ }\NormalTok{p_}\DecValTok{0}\NormalTok{)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(p_}\DecValTok{0} \OperatorTok{*}\StringTok{ }\NormalTok{(}\DecValTok{1} \OperatorTok{-}\StringTok{ }\NormalTok{p_}\DecValTok{0}\NormalTok{)}\OperatorTok{/}\NormalTok{n_Age) }

\CommentTok{# Cálculo de valores críticos para el valor de significación asignado}

\NormalTok{z_p.alfa =}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alfa) }

\CommentTok{# Cálculo del valor P en nuestro contraste de hipótesis}

\NormalTok{valor_p_Age =}\StringTok{ }\KeywordTok{pnorm}\NormalTok{(z_p) }

\KeywordTok{data.frame}\NormalTok{(n_Age, n_Age_Y, n_Age_O, p_hat, p_}\DecValTok{0}\NormalTok{, z_p, }\OperatorTok{-}\NormalTok{z_p.alfa, valor_p_Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   n_Age n_Age_Y n_Age_O     p_hat p_0       z_p X.z_p.alfa  valor_p_Age
## 1   342      70     272 0.2046784 0.5 -10.92291  -1.644854 4.478993e-28
\end{verbatim}

\textbf{OLGA} algo no va bien aquí, este -4.43 de donde sale? lo de
hombres y mujeres tampoco es correcto

Según el estadístico de contraste utilizado y el valor crítico
calculado, al ser el primero (-4.43) menor que el segundo (-1.64), al
0.05 de nivel de significancia, podemos rechazar la hipótesis nula de
que la proporción de supervivencia en hombres es mayor o igual a 50\%
respecto al de las mujeres.

De igual forma, al ser valor p casi nulo y por tanto menor que nuestro
nivel de significación (0.05), el valor p es significativo y podemos
rechazar, confirmando el contraste anterior, la hipótesis nula.

\textbf{¿La proporción de supervivencia en viajeros con billete único es
inferior a la de los viajeros con billete en conjunto?}

Hipótesis nula - H0: La proporción de viajeros con billete único que
sobreviven es igual o mayor a 50\% -\textgreater{} H0: p \textgreater=
p0, siendo po = 0.5\\
Hipótesis alternativa - H1: La proporción de viajeros con billete único
es menor a 50\% -\textgreater{} H1: p \textless{} p0, siendo po = 0.5

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Determinación del estadístico de contraste}

\NormalTok{train.survived_S <-}\StringTok{ }\NormalTok{train.survived[train.survived}\OperatorTok{$}\NormalTok{Count.ticket}\OperatorTok{==}\DecValTok{1}\NormalTok{,]}
\NormalTok{train.survived_My <-}\StringTok{ }\NormalTok{train.survived[train.survived}\OperatorTok{$}\NormalTok{Count.ticket}\OperatorTok{>}\DecValTok{1}\NormalTok{,]}

\NormalTok{n_Count.ticket <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived}\OperatorTok{$}\NormalTok{Count.ticket)}

\NormalTok{n_Count.ticket_S <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived_S}\OperatorTok{$}\NormalTok{Count.ticket)}

\NormalTok{n_Count.ticket_My <-}\StringTok{ }\KeywordTok{length}\NormalTok{(train.survived_My}\OperatorTok{$}\NormalTok{Count.ticket)}



\CommentTok{# Proporción muestral de menores}
\NormalTok{p_hat <-}\StringTok{ }\NormalTok{n_Count.ticket_S}\OperatorTok{/}\NormalTok{n_Count.ticket}

\CommentTok{# Proporción hipotesis nula}
\NormalTok{p_}\DecValTok{0}\NormalTok{ <-}\StringTok{ }\FloatTok{0.5}

\CommentTok{# Estadístico empleado z_p}
\NormalTok{z_p =}\StringTok{ }\NormalTok{(p_hat }\OperatorTok{-}\StringTok{ }\NormalTok{p_}\DecValTok{0}\NormalTok{)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(p_}\DecValTok{0} \OperatorTok{*}\StringTok{ }\NormalTok{(}\DecValTok{1} \OperatorTok{-}\StringTok{ }\NormalTok{p_}\DecValTok{0}\NormalTok{)}\OperatorTok{/}\NormalTok{n_Count.ticket) }

\CommentTok{# Cálculo de valores críticos para el valor de significación asignado}

\NormalTok{z_p.alfa =}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alfa) }

\CommentTok{# Cálculo del valor P en nuestro contraste de hipótesis}

\NormalTok{valor_p_Count.ticket =}\StringTok{ }\KeywordTok{pnorm}\NormalTok{(z_p) }

\KeywordTok{data.frame}\NormalTok{(n_Count.ticket, n_Count.ticket_S, n_Count.ticket_My, p_hat, p_}\DecValTok{0}\NormalTok{, z_p, }\OperatorTok{-}\NormalTok{z_p.alfa, valor_p_Count.ticket)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   n_Count.ticket n_Count.ticket_S n_Count.ticket_My    p_hat p_0       z_p X.z_p.alfa valor_p_Count.ticket
## 1            342              130               212 0.380117 0.5 -4.434052  -1.644854         4.623911e-06
\end{verbatim}

Según el estadístico de contraste utilizado y el valor crítico
calculado, al ser el primero (-10.92) menor que el segundo (-1.64), al
0.05 de nivel de significancia, podemos rechazar la hipótesis nula de
que la proporción de supervivencia en hombres es mayor o igual a 50\%
respecto al de las mujeres.

De igual forma, al ser valor p casi nulo y por tanto menor que nuestro
nivel de significación (0.05), el valor p es significativo y podemos
rechazar, confirmando el contraste anterior, la hipótesis nula.

\textbf{Relación entre supervivencia y billete único o grupal}

Utilizamos el test Chi cuadrado para comprobar si los pasajeros de
primera clase sobrevivieron en mayor medida que los pasajeros de segunda
clase.

El test se aplica en R con un nivel de confianza por defecto del 95\%.

Crearemos dos tablas de contingencia entre las variables que indican
supervencia y la que indica el tipo de billete. Una primera en valores
absolutos, y una segunda mostrando las proporciones.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Tabla de contingencia Survived - Tipo Billete}

\NormalTok{train}\OperatorTok{$}\NormalTok{ticket_tipo[train}\OperatorTok{$}\NormalTok{Count.ticket}\OperatorTok{==}\DecValTok{1}\NormalTok{] =}\StringTok{ "Único"}
\NormalTok{train}\OperatorTok{$}\NormalTok{ticket_tipo[train}\OperatorTok{$}\NormalTok{Count.ticket}\OperatorTok{!=}\DecValTok{1}\NormalTok{] =}\StringTok{ "Grupal"}

\NormalTok{train}\OperatorTok{$}\NormalTok{ticket_tipo <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(train}\OperatorTok{$}\NormalTok{ticket_tipo)}
\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Survived, train}\OperatorTok{$}\NormalTok{ticket_tipo, }\DataTypeTok{dnn =} \KeywordTok{c}\NormalTok{(}\StringTok{"Supervivencia"}\NormalTok{, }\StringTok{"Tipo Billete"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Tipo Billete
## Supervivencia Grupal Único
##             0    198   351
##             1    212   130
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Tabla de contingencia en proporciones Survived - Tipo Billete}
\KeywordTok{prop.table}\NormalTok{(}\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Survived, train}\OperatorTok{$}\NormalTok{ticket_tipo, }\DataTypeTok{dnn =} \KeywordTok{c}\NormalTok{(}\StringTok{"Supervivencia (%)"}\NormalTok{, }\StringTok{"Tipo Billete (%)"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Tipo Billete (%)
## Supervivencia (%)    Grupal     Único
##                 0 0.2222222 0.3939394
##                 1 0.2379349 0.1459035
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(train}\OperatorTok{$}\NormalTok{ticket_tipo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 891
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{length}\NormalTok{(train}\OperatorTok{$}\NormalTok{Survived)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 891
\end{verbatim}

Dos variables categóricas que forman parte de una tabla de contingencia
pueden ser sujetas a un test de independencia. Este test puede ser
representado for el ChiSquare Test mediante un contraste de hipótesis.

El contraste se realizará para observar si las dos variables son
independientes o no, por tanto, podemos plantear las hipótesis como se
indica a continuación:

Hipótesis nula - H0: Las variables Survived y Tipo Billete son
independientes.\\
Hipótesis alternativa - H1: Las variables Survived y Tipo Billete están
relacionadas.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Tabla de contingencia Survived y Tipo Billete}
\NormalTok{tabla_cont <-}\StringTok{ }\KeywordTok{table}\NormalTok{(train}\OperatorTok{$}\NormalTok{Survived, train}\OperatorTok{$}\NormalTok{ticket_tipo, }\DataTypeTok{dnn =} \KeywordTok{c}\NormalTok{(}\StringTok{"Supervivencia"}\NormalTok{, }\StringTok{"Tipo Billete"}\NormalTok{))}
\NormalTok{tabla_cont}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Tipo Billete
## Supervivencia Grupal Único
##             0    198   351
##             1    212   130
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Comprobación con la función chisq.test()}
\KeywordTok{chisq.test}\NormalTok{(tabla_cont)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's Chi-squared test with Yates' continuity correction
## 
## data:  tabla_cont
## X-squared = 55.966, df = 1, p-value = 7.375e-14
\end{verbatim}

El cálculo de los grados de libertad para una distribución Chi Square se
calcula como df = (c - 1)(r - 1) donde c es el número´de columnas y r el
número de filas. En nuestro caso c = r = 2, por lo tanto df = (2 - 1)(2
- 1) = 1.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Grados de libertad}

\NormalTok{gdl <-}\StringTok{ }\DecValTok{1}

\CommentTok{# Nivel de confianza}

\NormalTok{ndc <-}\StringTok{ }\FloatTok{0.95}


\CommentTok{# Valor Crítico}
\NormalTok{val_cri <-}\StringTok{ }\KeywordTok{qchisq}\NormalTok{(ndc, gdl)}
\NormalTok{val_cri}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3.841459
\end{verbatim}

Debido a que el estadístico Chi Square es mayor al valor crítico
calculado de la distribución Chi Square (con un grado de libertad y con
un nivel de significación de 0.05), podemos rechazar la hipótesis nula
de que no hay relación entre Survived y Tipo de Billete, es decir,
rechazamos la hipótesis al 95 \% de nivel de confianza de que tales
variables sean independientes.

Como el valor de p es menor que el nivel de significancia, podemos
rechazar la hipótesis nula de que las variables Survived y Tipo de
Billete son independientes, cuadrando este resultado con los cálculos
anteriores.

Por tanto, se puede afirmar al 95\% de nivel de confianza que las
variables Survived y Tipo de Billete \textbf{están relacionadas}.

\textbf{Contraste de hipótesis sobre la edad de supervivencia}

Planteamos la pregunta de investigación: Queremos saber si las personas
que sobrevivieron eran más jóvenes que las personas que murieron en el
accidente o, por el contrario, la edad para las personas que muerieron y
sobrevivieron es similar.

Nos encontramos ante el caso en el que podemos asumir la normalidad de
las distribuciones de la media de las dos muestras pero sabemos que las
varianzas de las muestras \textbf{(EL RESULTADO HA CAMBIADO)} son
diferentes. Se trata de un test paramétrico de dos muestras.
\textbf{OLGA: ok, entonces var.equal = TRUE}

H0: La media de edad de las personas supervivientes es la misma que de
las personas que muerieron\\
H1: La media de edad de las personas que murieron es mayor que la de las
personas supervivientes.

Usamos un test paramétrico definido por \texttt{t.test}

Con un valor p-value igual por debajo de 0.05 podemos aceptar la
hipótesis H1. Con un nivel de confianza del 95\% afirmamos que las
personas que murieron en el Titanic tienen una media de edad más alta
que las personas que sobrevivieron.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(train.not.survived}\OperatorTok{$}\NormalTok{Age, train.survived}\OperatorTok{$}\NormalTok{Age, }\DataTypeTok{alternative=}\StringTok{"greater"}\NormalTok{, }\DataTypeTok{var.equal=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  train.not.survived$Age and train.survived$Age
## t = 2.5263, df = 889, p-value = 0.005849
## alternative hypothesis: true difference in means is greater than 0
## 95 percent confidence interval:
##  0.8503831       Inf
## sample estimates:
## mean of x mean of y 
##  30.38251  27.94056
\end{verbatim}

\textbf{Correlaciones}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Relaciones cruzadas de las variables cuantitativas (correlaciones) para todos los datos.}

\NormalTok{col_var_cuantitativa_sin_ID <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Age"}\NormalTok{, }\StringTok{"SibSp"}\NormalTok{, }\StringTok{"Parch"}\NormalTok{, }\StringTok{"Count.ticket"}\NormalTok{, }\StringTok{"Unit.price"}\NormalTok{)}

\NormalTok{df_var_cuantitativa <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[, col_var_cuantitativa_sin_ID]}


\KeywordTok{pairs.panels}\NormalTok{(df_var_cuantitativa[,col_var_cuantitativa_sin_ID], }
             \DataTypeTok{method =} \StringTok{"pearson"}\NormalTok{, }
             \DataTypeTok{hist.col =} \StringTok{"grey"}\NormalTok{,}
             \DataTypeTok{density =} \OtherTok{TRUE}\NormalTok{,  }
             \DataTypeTok{ellipses =} \OtherTok{TRUE} 
\NormalTok{             )}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-65-1} \end{center}

\textbf{OLGA} Para algunos modelos necesitaremos la variable en forma de
texto, por lo tanto guardamos un dato alternativo sobre la supervivencia
de los pasajeros: ``Survived'' para el valor 1 y ``Died'' para el valor
0 de la variable dependiente.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train}\OperatorTok{$}\NormalTok{survived <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(train}\OperatorTok{$}\NormalTok{Survived}\OperatorTok{==}\DecValTok{1}\NormalTok{, }\StringTok{"Survived"}\NormalTok{, }\StringTok{"Died"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X <-}\StringTok{ }\NormalTok{train[}\KeywordTok{c}\NormalTok{(}\StringTok{"Pclass"}\NormalTok{, }\StringTok{"Sex"}\NormalTok{, }\StringTok{"Age"}\NormalTok{, }\StringTok{"SibSp"}\NormalTok{, }\StringTok{"Parch"}\NormalTok{, }\StringTok{"Count.ticket"}\NormalTok{, }\StringTok{"Unit.price"}\NormalTok{, }\StringTok{"Embarked"}\NormalTok{)]}

\NormalTok{y <-}\StringTok{ }\NormalTok{train[}\DecValTok{9}\NormalTok{]}
\NormalTok{y}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }\NormalTok{train[}\DecValTok{10}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

Partimos el conjunto train en subconjuntos de train y validación. De
esta manera dispondremos de datos para comprobar el funcionamiento de
los modelos que construyamos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{indexes =}\StringTok{ }\KeywordTok{sample}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(train), }\DataTypeTok{size=}\KeywordTok{floor}\NormalTok{((}\DecValTok{2}\OperatorTok{/}\DecValTok{3}\NormalTok{)}\OperatorTok{*}\KeywordTok{nrow}\NormalTok{(train)))}
\NormalTok{trainX<-X[indexes,]}
\NormalTok{trainy<-y[indexes,]}
\NormalTok{validX<-X[}\OperatorTok{-}\NormalTok{indexes,]}
\NormalTok{validy<-y[}\OperatorTok{-}\NormalTok{indexes,]}
\NormalTok{train}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(trainX, trainy))}
\NormalTok{trainy}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }\NormalTok{y}\FloatTok{.1}\NormalTok{[indexes,]}
\NormalTok{validy}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }\NormalTok{y}\FloatTok{.1}\NormalTok{[}\OperatorTok{-}\NormalTok{indexes,]}
\end{Highlighting}
\end{Shaded}

\textbf{Regresión}

Aplicamos una regresión logística para predecir la probabilidad de
supervivencia usando como variable predictora la variable sexo.

Según los datos que nos proporciona la función \texttt{summary} la
variable sexo es significativa para predecir la supervivencia y ser de
sexo masculino reduce la probabilidad de sobrevivir.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#model0=glm(formula=Survived~Sex, data=train, family=binomial(link=logit))}
\NormalTok{model0=}\KeywordTok{glm}\NormalTok{(}\DataTypeTok{formula=}\NormalTok{trainy}\OperatorTok{~}\NormalTok{Sex, }\DataTypeTok{data=}\NormalTok{train}\FloatTok{.1}\NormalTok{, }\DataTypeTok{family=}\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link=}\NormalTok{logit))}

\KeywordTok{summary}\NormalTok{(model0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = trainy ~ Sex, family = binomial(link = logit), 
##     data = train.1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6380  -0.6571  -0.6571   0.7786   1.8106  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)   1.0384     0.1541   6.737 1.62e-11 ***
## Sexmale      -2.4616     0.2019 -12.194  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 796.53  on 593  degrees of freedom
## Residual deviance: 620.64  on 592  degrees of freedom
## AIC: 624.64
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

Calculamos los Odds Ratio. Los odds ratio indican que ser hombre es
factor de protección para la clase 1 (sobrevivir). Los hombres están
``protegidos'' de la supervivencia en comparación con las mujeres.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coefficients}\NormalTok{(model0))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)     Sexmale 
##  2.82456140  0.08529611
\end{verbatim}

Usamos los datos de validación para realizar una predicción de
supervivencia. Tenemos que 75 instancias de supervivencia y 157
instancias de no supervivencia han sido predichas correctamente. 39
instancias de supervivencia real han sido predichas como no
supervivencia. 26 instancias de no supervivencia fueron predichas
incorrectamente como supervivencia.

El modelo de regresión que utiliza únicamente la variable Sexo para
predecir la supervivencia tiene una precisión del 78\%.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newdata <-}\StringTok{ }\NormalTok{validX}
\NormalTok{probabilities <-}\StringTok{ }\NormalTok{model0 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{predict}\NormalTok{(newdata[}\KeywordTok{c}\NormalTok{(}\StringTok{"Sex"}\NormalTok{)], }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{predicted.classes <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(probabilities }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\CommentTok{# Matriz de confusión}
\NormalTok{conf}\FloatTok{.1}\NormalTok{ <-}\StringTok{ }\KeywordTok{table}\NormalTok{(validy, predicted.classes)}
\NormalTok{conf}\FloatTok{.1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       predicted.classes
## validy   0   1
##      0 165  24
##      1  36  72
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Precisión}
\KeywordTok{sum}\NormalTok{(}\KeywordTok{diag}\NormalTok{(conf}\FloatTok{.1}\NormalTok{))}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(conf}\FloatTok{.1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7979798
\end{verbatim}

Aplicamos una regresión logística para comprobar si las variables Sexo y
Clase son significativas para la supervivencia en el accidente.

Ambas variables son significativas y así lo indican los asteriscos junto
a los valores Pr(\textgreater\textbar z\textbar).

Ser hombre, viajar en clase 2 o clase 3 reduce la posibilidad de
supervivencia con respecto a ser mujer y viajar en primera clase. Esto
viene indicado por el signo negativo que acompaña el valor del
coeficiente para Sexmale, Pclass2 y Pclass3.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model1=}\KeywordTok{glm}\NormalTok{(}\DataTypeTok{formula=}\NormalTok{trainy}\OperatorTok{~}\NormalTok{Sex}\OperatorTok{+}\KeywordTok{as.factor}\NormalTok{(Pclass), }\DataTypeTok{data=}\NormalTok{train}\FloatTok{.1}\NormalTok{, }\DataTypeTok{family=}\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link=}\NormalTok{logit))}
\KeywordTok{summary}\NormalTok{(model1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = trainy ~ Sex + as.factor(Pclass), family = binomial(link = logit), 
##     data = train.1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2389  -0.7626  -0.4272   0.6072   2.2088  
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(>|z|)    
## (Intercept)          2.4213     0.2735   8.852  < 2e-16 ***
## Sexmale             -2.6835     0.2300 -11.670  < 2e-16 ***
## as.factor(Pclass)2  -0.8241     0.2995  -2.752  0.00593 ** 
## as.factor(Pclass)3  -2.0859     0.2683  -7.775 7.56e-15 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 796.53  on 593  degrees of freedom
## Residual deviance: 547.61  on 590  degrees of freedom
## AIC: 555.61
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

Calculamos los odds ratio. Igual que en el caso anterior vemos que la
probabilidad ser hombre y sobrevivir es mucho menor que la de ser mujer
y sobrevivir. Por clases el OR indica que estar en segunda o tercera
clase es factor de protección (pocas probable sobrevivir) respecto a la
primera clase.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coefficients}\NormalTok{(model1))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        (Intercept)            Sexmale as.factor(Pclass)2 as.factor(Pclass)3 
##        11.26038128         0.06832221         0.43863173         0.12419256
\end{verbatim}

Realizamos la predicción sobre el conjunto de validación que obtuvimos y
con el resultado creamos una matriz de confusión y calculamos la
precisión. El resultado es igual que en la regresión anterior.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probabilities1 <-}\StringTok{ }\NormalTok{model1 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{predict}\NormalTok{(newdata[}\KeywordTok{c}\NormalTok{(}\StringTok{"Sex"}\NormalTok{,}\StringTok{"Pclass"}\NormalTok{)], }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{predicted.classes1 <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(probabilities1 }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\CommentTok{# Matriz de confusión}
\NormalTok{conf}\FloatTok{.2}\NormalTok{ <-}\StringTok{ }\KeywordTok{table}\NormalTok{(validy, predicted.classes1)}
\NormalTok{conf}\FloatTok{.2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       predicted.classes1
## validy   0   1
##      0 165  24
##      1  36  72
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Precisión}
\KeywordTok{sum}\NormalTok{(}\KeywordTok{diag}\NormalTok{(conf}\FloatTok{.2}\NormalTok{)) }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(conf}\FloatTok{.2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7979798
\end{verbatim}

Por último generamos un modelo que incluye todas las variables
disponibles

En los datos hemos detectado que había hasta 8 pasajeros con el mismo
billete. Posiblemente se tratara de familia o amigos. Usaremos esta
variable para crear un modelo.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model2=}\KeywordTok{glm}\NormalTok{(}\DataTypeTok{formula=}\NormalTok{trainy}\OperatorTok{~}\NormalTok{Pclass}\OperatorTok{+}\NormalTok{Sex}\OperatorTok{+}\NormalTok{Age}\OperatorTok{+}\KeywordTok{factor}\NormalTok{(Count.ticket)}\OperatorTok{+}\NormalTok{Embarked, }\DataTypeTok{data=}\NormalTok{train}\FloatTok{.1}\NormalTok{, }\DataTypeTok{family=}\KeywordTok{binomial}\NormalTok{(}\DataTypeTok{link=}\NormalTok{logit))}
\KeywordTok{summary}\NormalTok{(model2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = trainy ~ Pclass + Sex + Age + factor(Count.ticket) + 
##     Embarked, family = binomial(link = logit), data = train.1)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2370  -0.5767  -0.3775   0.6072   2.7732  
## 
## Coefficients:
##                          Estimate Std. Error z value Pr(>|z|)    
## (Intercept)              5.509044   0.712389   7.733 1.05e-14 ***
## Pclass                  -1.361484   0.176220  -7.726 1.11e-14 ***
## Sexmale                 -2.829007   0.257077 -11.004  < 2e-16 ***
## Age                     -0.034616   0.009634  -3.593 0.000327 ***
## factor(Count.ticket)2   -0.116956   0.297710  -0.393 0.694430    
## factor(Count.ticket)3    0.475500   0.349707   1.360 0.173922    
## factor(Count.ticket)4    0.171720   0.681568   0.252 0.801081    
## factor(Count.ticket)5   -1.730097   0.679061  -2.548 0.010841 *  
## factor(Count.ticket)6   -2.465045   1.053632  -2.340 0.019306 *  
## factor(Count.ticket)7   -1.601428   0.839236  -1.908 0.056366 .  
## factor(Count.ticket)8    1.705406   0.702943   2.426 0.015262 *  
## factor(Count.ticket)11 -15.359270 511.190364  -0.030 0.976030    
## EmbarkedQ                0.187635   0.505620   0.371 0.710564    
## EmbarkedS               -0.169267   0.299200  -0.566 0.571576    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 796.53  on 593  degrees of freedom
## Residual deviance: 501.31  on 580  degrees of freedom
## AIC: 529.31
## 
## Number of Fisher Scoring iterations: 14
\end{verbatim}

El resultado del modelo indica que cuando tres o cuatro personas
viajaban juntas, la probabilidad de sobrevivir aumentaba (signo positivo
del coeficiente).

Calculamos los ORS. Para las personas que viajaban con otra persona,
otras dos o tres personas el ``riesgo'' de sobrevivir es mucho mayor.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coefficients}\NormalTok{(model2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            (Intercept)                 Pclass                Sexmale                    Age  factor(Count.ticket)2  factor(Count.ticket)3  factor(Count.ticket)4  factor(Count.ticket)5  factor(Count.ticket)6  factor(Count.ticket)7  factor(Count.ticket)8 factor(Count.ticket)11              EmbarkedQ              EmbarkedS 
##           2.469150e+02           2.562801e-01           5.907148e-02           9.659761e-01           8.896246e-01           1.608819e+00           1.187345e+00           1.772673e-01           8.500503e-02           2.016084e-01           5.503620e+00           2.135766e-07           1.206393e+00           8.442832e-01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{probabilities2 <-}\StringTok{ }\NormalTok{model2 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{predict}\NormalTok{(newdata[}\KeywordTok{c}\NormalTok{(}\StringTok{"Pclass"}\NormalTok{,}\StringTok{"Sex"}\NormalTok{,}\StringTok{"Age"}\NormalTok{,}\StringTok{"Count.ticket"}\NormalTok{, }\StringTok{"Embarked"}\NormalTok{)], }\DataTypeTok{type =} \StringTok{"response"}\NormalTok{)}
\NormalTok{predicted.classes2 <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(probabilities2 }\OperatorTok{>}\StringTok{ }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\CommentTok{# Matriz de confusión}
\NormalTok{conf}\FloatTok{.3}\NormalTok{ <-}\StringTok{ }\KeywordTok{table}\NormalTok{(validy, predicted.classes2)}
\NormalTok{conf}\FloatTok{.3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       predicted.classes2
## validy   0   1
##      0 166  23
##      1  32  76
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Precisión}

\KeywordTok{sum}\NormalTok{(}\KeywordTok{diag}\NormalTok{(conf}\FloatTok{.3}\NormalTok{)) }\OperatorTok{/}\StringTok{ }\KeywordTok{sum}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(conf}\FloatTok{.3}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8148148
\end{verbatim}

\textbf{OLGA: Me preguntabas los modelos supervisados o no: ya estaba
hecho el árbol rpart, he hecho otro rpart con cross validation y un
random forest que no parece dar mejor resultado. Con esto yo creo que
más que suficiente}

\textbf{Árboles de decisión CART}

En primer lugar creamos un árbol de decisión para predecir la
supervivencia de los pasajeros del Titanic tomando en cuanta las
variables explicatovas del conjunto de entrenamiento y la etiqueta de
clase (Supervivencia o no)

\begin{verbatim}
## Warning: package 'rpart.plot' was built under R version 4.0.5
\end{verbatim}

\begin{verbatim}
## Loading required package: rpart
\end{verbatim}

\begin{verbatim}
## Warning: package 'rpart' was built under R version 4.0.5
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'rpart'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:faraway':
## 
##     solder
\end{verbatim}

\begin{verbatim}
## Warning: package 'caret' was built under R version 4.0.5
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'caret'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:DescTools':
## 
##     MAE, RMSE
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:InformationValue':
## 
##     confusionMatrix, precision, sensitivity, specificity
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:purrr':
## 
##     lift
\end{verbatim}

Usamos los datos del conjunto train para entrenar el modelo y
visualizamos el árbol y los datos del modelo.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{treeFit <-}\StringTok{ }\KeywordTok{rpart}\NormalTok{(trainy}\OperatorTok{~}\NormalTok{.,}\DataTypeTok{data=}\NormalTok{trainX,}\DataTypeTok{method =}\StringTok{'class'}\NormalTok{)}
\KeywordTok{print}\NormalTok{(treeFit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## n= 594 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
##  1) root 594 234 0 (0.60606061 0.39393939)  
##    2) Sex=male 376  73 0 (0.80585106 0.19414894)  
##      4) Unit.price< 24.40417 298  41 0 (0.86241611 0.13758389)  
##        8) Age>=3.5 286  33 0 (0.88461538 0.11538462) *
##        9) Age< 3.5 12   4 1 (0.33333333 0.66666667) *
##      5) Unit.price>=24.40417 78  32 0 (0.58974359 0.41025641)  
##       10) Age>=53 14   1 0 (0.92857143 0.07142857) *
##       11) Age< 53 64  31 0 (0.51562500 0.48437500)  
##         22) Unit.price>=35.9 14   3 0 (0.78571429 0.21428571) *
##         23) Unit.price< 35.9 50  22 1 (0.44000000 0.56000000)  
##           46) Age>=28.5 39  19 0 (0.51282051 0.48717949)  
##             92) SibSp>=0.5 11   3 0 (0.72727273 0.27272727) *
##             93) SibSp< 0.5 28  12 1 (0.42857143 0.57142857) *
##           47) Age< 28.5 11   2 1 (0.18181818 0.81818182) *
##    3) Sex=female 218  57 1 (0.26146789 0.73853211)  
##      6) Pclass>=2.5 104  51 0 (0.50961538 0.49038462)  
##       12) Count.ticket>=4 20   1 0 (0.95000000 0.05000000) *
##       13) Count.ticket< 4 84  34 1 (0.40476190 0.59523810)  
##         26) Unit.price>=8.09375 12   2 0 (0.83333333 0.16666667) *
##         27) Unit.price< 8.09375 72  24 1 (0.33333333 0.66666667)  
##           54) Age>=27.5 13   5 0 (0.61538462 0.38461538) *
##           55) Age< 27.5 59  16 1 (0.27118644 0.72881356) *
##      7) Pclass< 2.5 114   4 1 (0.03508772 0.96491228) *
\end{verbatim}

El árbol ha realizado las particiones de los datos en base a la variable
Sex. Los pasajeros de sexo masculino, mayores de 14 años tienen como
clase por defecto la no supervivencia. Los pasajeros que pagaron entre
26 y 31 dólares y menores de 52 años no sobreviven. Los pasajeros
menores de 14 años si viajaban con menos de 3 hermanos casi todos
sobreviven.

Por otra parte, los pasajeros de sexo Femenino en que viajaban en
tercera clase sobrevivieron si viajaban con menos de 5 personas (count
ticket), si pagaron menos de 8.1 dólares y si tenían edad menor de 28
años. Todos los demás se clasifican como no supervivientes. Las mujeres
en otras clases distintas de la tercera sobrevivieron en su mayoría.

En el árbol podemos ver que se ha considerado variables bastante
diferentes para clasificar a los hombres y a las mujeres. Para los
hombres la edad ha sido un factor importante para la supervivencia,
principalmente sobrevivieron los hombres menores de 14 años. En el caso
de las mujeres el factor determinante ha sido la clase y las personas
con las que viajaban.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Árbol resultante.  }
\KeywordTok{rpart.plot}\NormalTok{(treeFit)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-80-1} \end{center}

Predecimos usando los datos de validación.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prediction <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(treeFit,}\DataTypeTok{newdata=}\NormalTok{validX,}\DataTypeTok{type =}\StringTok{'class'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Con la matriz de confusión y el valor de Accuracy podemos ver que la
predicción ha mejorado con respecto a la regresión logística.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{confusionMatrix}\NormalTok{(prediction,validy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 168  34
##          1  21  74
##                                           
##                Accuracy : 0.8148          
##                  95% CI : (0.7659, 0.8573)
##     No Information Rate : 0.6364          
##     P-Value [Acc > NIR] : 1.344e-11       
##                                           
##                   Kappa : 0.5893          
##                                           
##  Mcnemar's Test P-Value : 0.1056          
##                                           
##             Sensitivity : 0.8889          
##             Specificity : 0.6852          
##          Pos Pred Value : 0.8317          
##          Neg Pred Value : 0.7789          
##              Prevalence : 0.6364          
##          Detection Rate : 0.5657          
##    Detection Prevalence : 0.6801          
##       Balanced Accuracy : 0.7870          
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

\textbf{Árbol de decisión usando cross validation y búsqueda de mejor
parámetro}

Podemos entrenar un árbol de decisión usando cross validation y la
búsqueda en rejilla.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(caret)}
\KeywordTok{library}\NormalTok{(lattice)}

\NormalTok{control <-}\StringTok{  }\KeywordTok{trainControl}\NormalTok{(}\DataTypeTok{method=}\StringTok{"repeatedcv"}\NormalTok{, }\DataTypeTok{number=}\DecValTok{3}\NormalTok{, }\DataTypeTok{repeats=}\DecValTok{3}\NormalTok{, }\DataTypeTok{savePredictions =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{metric <-}\StringTok{ "Accuracy"}
\NormalTok{grid <-}\StringTok{ }\KeywordTok{expand.grid}\NormalTok{(}\DataTypeTok{cp =} \KeywordTok{seq}\NormalTok{(}\FloatTok{0.0001}\NormalTok{,}\FloatTok{0.05}\NormalTok{,}\FloatTok{0.001}\NormalTok{))}
\CommentTok{# Training of model.}
\NormalTok{model.boost <-}\StringTok{ }\KeywordTok{train}\NormalTok{(}\DataTypeTok{y=}\KeywordTok{as.factor}\NormalTok{(trainy), }\DataTypeTok{tuneGrid=}\NormalTok{grid,}\DataTypeTok{x=}\NormalTok{trainX, }\DataTypeTok{method=}\StringTok{"rpart"}\NormalTok{,}\DataTypeTok{metric=}\NormalTok{metric, }\DataTypeTok{trControl=}\NormalTok{control)}

\CommentTok{# Summarize the results}
\KeywordTok{print}\NormalTok{(model.boost)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## CART 
## 
## 594 samples
##   8 predictor
##   2 classes: '0', '1' 
## 
## No pre-processing
## Resampling: Cross-Validated (3 fold, repeated 3 times) 
## Summary of sample sizes: 396, 396, 396, 396, 396, 396, ... 
## Resampling results across tuning parameters:
## 
##   cp      Accuracy   Kappa    
##   0.0001  0.8125701  0.6021782
##   0.0011  0.8148148  0.6065598
##   0.0021  0.8148148  0.6065598
##   0.0031  0.8148148  0.6065598
##   0.0041  0.8148148  0.6065598
##   0.0051  0.8142536  0.6042930
##   0.0061  0.8142536  0.6042930
##   0.0071  0.8125701  0.6016643
##   0.0081  0.8125701  0.6016643
##   0.0091  0.8125701  0.6010345
##   0.0101  0.8159371  0.6057246
##   0.0111  0.8131313  0.5977968
##   0.0121  0.8131313  0.5977968
##   0.0131  0.8058361  0.5824903
##   0.0141  0.8058361  0.5824903
##   0.0151  0.8058361  0.5824903
##   0.0161  0.8058361  0.5824903
##   0.0171  0.8069585  0.5833717
##   0.0181  0.8058361  0.5792408
##   0.0191  0.8058361  0.5792408
##   0.0201  0.8024691  0.5721406
##   0.0211  0.8024691  0.5721406
##   0.0221  0.8024691  0.5721406
##   0.0231  0.8024691  0.5721406
##   0.0241  0.8041526  0.5733845
##   0.0251  0.8041526  0.5733845
##   0.0261  0.8035915  0.5727827
##   0.0271  0.8035915  0.5727827
##   0.0281  0.8035915  0.5727827
##   0.0291  0.8035915  0.5727827
##   0.0301  0.8035915  0.5727827
##   0.0311  0.8035915  0.5727827
##   0.0321  0.8047138  0.5747368
##   0.0331  0.8047138  0.5747368
##   0.0341  0.8047138  0.5747368
##   0.0351  0.8047138  0.5747368
##   0.0361  0.8007856  0.5670725
##   0.0371  0.8007856  0.5670725
##   0.0381  0.8007856  0.5670725
##   0.0391  0.7906846  0.5486385
##   0.0401  0.7906846  0.5486385
##   0.0411  0.7895623  0.5489757
##   0.0421  0.7839506  0.5380622
##   0.0431  0.7839506  0.5380622
##   0.0441  0.7839506  0.5380622
##   0.0451  0.7839506  0.5380622
##   0.0461  0.7839506  0.5380622
##   0.0471  0.7839506  0.5380622
##   0.0481  0.7833895  0.5393605
##   0.0491  0.7833895  0.5393605
## 
## Accuracy was used to select the optimal model using the largest value.
## The final value used for the model was cp = 0.0101.
\end{verbatim}

Haremos la validación cruzada o crossvalidation con 10 folds y busqueda
de los mejores parámetros usando el expand.grid. Utilizaremos la métrica
Accuracy que mide el porcentaje de instancias correctas sobre total.
Entrenamos el modelo con los datos trainX y trainy, establecemos el
método que es el mismo que aplicamos en el primer árbol de decisión de
la pec (C5.0) como parámetro de la función.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model.boost}\OperatorTok{$}\NormalTok{finalModel}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## n= 594 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
##  1) root 594 234 0 (0.60606061 0.39393939)  
##    2) Sex=male 376  73 0 (0.80585106 0.19414894)  
##      4) Unit.price< 24.40417 298  41 0 (0.86241611 0.13758389)  
##        8) Age>=3.5 286  33 0 (0.88461538 0.11538462) *
##        9) Age< 3.5 12   4 1 (0.33333333 0.66666667) *
##      5) Unit.price>=24.40417 78  32 0 (0.58974359 0.41025641)  
##       10) Age>=53 14   1 0 (0.92857143 0.07142857) *
##       11) Age< 53 64  31 0 (0.51562500 0.48437500)  
##         22) Unit.price>=35.9 14   3 0 (0.78571429 0.21428571) *
##         23) Unit.price< 35.9 50  22 1 (0.44000000 0.56000000)  
##           46) Age>=28.5 39  19 0 (0.51282051 0.48717949)  
##             92) SibSp>=0.5 11   3 0 (0.72727273 0.27272727) *
##             93) SibSp< 0.5 28  12 1 (0.42857143 0.57142857) *
##           47) Age< 28.5 11   2 1 (0.18181818 0.81818182) *
##    3) Sex=female 218  57 1 (0.26146789 0.73853211)  
##      6) Pclass>=2.5 104  51 0 (0.50961538 0.49038462)  
##       12) Count.ticket>=4 20   1 0 (0.95000000 0.05000000) *
##       13) Count.ticket< 4 84  34 1 (0.40476190 0.59523810)  
##         26) Unit.price>=8.09375 12   2 0 (0.83333333 0.16666667) *
##         27) Unit.price< 8.09375 72  24 1 (0.33333333 0.66666667)  
##           54) Age>=27.5 13   5 0 (0.61538462 0.38461538) *
##           55) Age< 27.5 59  16 1 (0.27118644 0.72881356) *
##      7) Pclass< 2.5 114   4 1 (0.03508772 0.96491228) *
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prediction <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(}\KeywordTok{predict}\NormalTok{(model.boost}\OperatorTok{$}\NormalTok{finalModel, }\DataTypeTok{newdata=}\NormalTok{validX)[,}\DecValTok{1}\NormalTok{]}\OperatorTok{>}\FloatTok{0.50}\NormalTok{, }\StringTok{"0"}\NormalTok{, }\StringTok{"1"}\NormalTok{)}

\KeywordTok{table}\NormalTok{(prediction, validy)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           validy
## prediction   0   1
##          0 168  34
##          1  21  74
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{rpart.plot}\NormalTok{(model.boost}\OperatorTok{$}\NormalTok{finalModel, }\DataTypeTok{box.col=}\KeywordTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-85-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model.boost}\OperatorTok{$}\NormalTok{levels}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "0" "1"
## attr(,"ordered")
## [1] FALSE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(model.boost)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{GarcesOlga_AcostaCarlos_PRA2_files/figure-latex/unnamed-chunk-87-1} \end{center}

Visualizamos las iteraciones de boosting vs la precisión. Tenemos la
mayor precisión con 25 iteraciones.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicted_model.boost <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(model.boost, }\DataTypeTok{newdata=}\NormalTok{validX)}
\NormalTok{cmat <-}\StringTok{ }\KeywordTok{confusionMatrix}\NormalTok{(predicted_model.boost, }\KeywordTok{as.factor}\NormalTok{(validy))}
\NormalTok{cmat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 168  34
##          1  21  74
##                                           
##                Accuracy : 0.8148          
##                  95% CI : (0.7659, 0.8573)
##     No Information Rate : 0.6364          
##     P-Value [Acc > NIR] : 1.344e-11       
##                                           
##                   Kappa : 0.5893          
##                                           
##  Mcnemar's Test P-Value : 0.1056          
##                                           
##             Sensitivity : 0.8889          
##             Specificity : 0.6852          
##          Pos Pred Value : 0.8317          
##          Neg Pred Value : 0.7789          
##              Prevalence : 0.6364          
##          Detection Rate : 0.5657          
##    Detection Prevalence : 0.6801          
##       Balanced Accuracy : 0.7870          
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Defining the training controls for multiple models}
\NormalTok{fitControl <-}\StringTok{ }\KeywordTok{trainControl}\NormalTok{(}
  \DataTypeTok{method =} \StringTok{"repeatedcv"}\NormalTok{,}
  \DataTypeTok{number =} \DecValTok{5}\NormalTok{,}
  \DataTypeTok{repeats =} \DecValTok{3}\NormalTok{,}
\DataTypeTok{savePredictions =} \StringTok{'final'}\NormalTok{,}
\DataTypeTok{classProbs =}\NormalTok{ T)}

\CommentTok{#Defining the predictors and outcome}
\NormalTok{predictors<-}\KeywordTok{colnames}\NormalTok{(trainX)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Training the random forest model}
\CommentTok{#model_rf<-train(trainX,y=as.factor(trainy.1),method='rf',trControl=fitControl,tuneLength=9)}

\CommentTok{#Predicting using random forest model}
\CommentTok{#validX$pred_rf<-predict(object = model_rf,validX)}

\CommentTok{#Checking the accuracy of the random forest model}
\CommentTok{#confusionMatrix(as.factor(validy.1),validX$pred_rf)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#plot(model_rf)}
\end{Highlighting}
\end{Shaded}

\hypertarget{including-plots}{%
\subsection{Including Plots}\label{including-plots}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{representaciuxf3n-de-resultados}{%
\section{\texorpdfstring{\textbf{Representación de
resultados}}{Representación de resultados}}\label{representaciuxf3n-de-resultados}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{tabla-resumen-de-las-variables-cualitativas-datos-completos}{%
\subsection{Tabla resumen de las variables cualitativas (datos
completos)}\label{tabla-resumen-de-las-variables-cualitativas-datos-completos}}

Realizaremos una tabla resumen con las frecuencias relativas y las
frecuencias absolutas de las variables cualitativas. Creamos un
dataframe auxiliar para generar nuestra tabla.

Calculamos, para todos los campos, la frecuencia relativa y absoluta a
través del contaje dividido por el número total de filas del dataframe.

Creamos una tabla mediante la función kable().

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{col_var_cualitativa_sin_ID <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Pclass"}\NormalTok{, }\StringTok{"Sex"}\NormalTok{, }\StringTok{"Embarked"}\NormalTok{)}

\NormalTok{df_var_cualitativa <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[, col_var_cualitativa_sin_ID]}

\NormalTok{df_var_cualitativa}\OperatorTok{$}\NormalTok{Sex <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Sex)}
\NormalTok{df_var_cualitativa}\OperatorTok{$}\NormalTok{Embarked <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Embarked)}


\CommentTok{# Frecuencias relativas y absolutas de campo PClass}
\NormalTok{Pclass_table_frec <-}\StringTok{ }\NormalTok{(}\KeywordTok{count}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Pclass))}
\NormalTok{Pclass_table_cum <-}\StringTok{ }\NormalTok{(}\KeywordTok{count}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Pclass)}\OperatorTok{/}\KeywordTok{dim}\NormalTok{(df_var_cualitativa)[}\DecValTok{1}\NormalTok{])[}\DecValTok{2}\NormalTok{]}

\NormalTok{Pclass_table <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{ (Pclass_table_frec, Pclass_table_cum)}

\CommentTok{# Frecuencias relativas y absolutas de campo Sex}
\NormalTok{Sex_table_frec <-}\StringTok{ }\NormalTok{(}\KeywordTok{count}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Sex))}
\NormalTok{Sex_table_cum <-}\StringTok{ }\NormalTok{(}\KeywordTok{count}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Sex)}\OperatorTok{/}\KeywordTok{dim}\NormalTok{(df_var_cualitativa)[}\DecValTok{1}\NormalTok{])[}\DecValTok{2}\NormalTok{]}

\NormalTok{Sex_table <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{ (Sex_table_frec, Sex_table_cum)}

\CommentTok{# Frecuencias relativas y absolutas de campo Embarked}
\NormalTok{Embarked_table_frec <-}\StringTok{ }\NormalTok{(}\KeywordTok{count}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Embarked))}
\NormalTok{Embarked_table_cum <-}\StringTok{ }\NormalTok{(}\KeywordTok{count}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Embarked)}\OperatorTok{/}\KeywordTok{dim}\NormalTok{(df_var_cualitativa)[}\DecValTok{1}\NormalTok{])[}\DecValTok{2}\NormalTok{]}

\NormalTok{Embarked_table <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{ (Embarked_table_frec, Embarked_table_cum)}



\CommentTok{# Unión de toda la tabla asignando el nombre de las columnas}
\NormalTok{df_var_cualitativa_table <-}\StringTok{ }\KeywordTok{rbind.data.frame}\NormalTok{(Pclass_table, Sex_table, Embarked_table)}
\KeywordTok{colnames}\NormalTok{(df_var_cualitativa_table) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Variable Cualitativa"}\NormalTok{, }\StringTok{"Frecuencia Absoluta"}\NormalTok{, }\StringTok{"Frecuencia Relativa"}\NormalTok{)}

\CommentTok{# Variables auxiliares para la creación de la tabla kable() de forma más automática.}

\CommentTok{# Dimensiones de cada grupo de la tabla}
\NormalTok{dim_grupo1_ =}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Pclass))}
\NormalTok{dim_grupo2_ =}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Sex))}
\NormalTok{dim_grupo3_ =}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{unique}\NormalTok{(df_var_cualitativa}\OperatorTok{$}\NormalTok{Embarked))}



\CommentTok{# Límites de las posiciones de los grupos (automatico)}
\NormalTok{dim1_i <-}\StringTok{ }\DecValTok{1}
\NormalTok{dim1_f <-}\StringTok{ }\NormalTok{dim_grupo1_}
\NormalTok{dim2_i <-}\StringTok{ }\NormalTok{dim1_f }\OperatorTok{+}\DecValTok{1}
\NormalTok{dim2_f <-}\StringTok{ }\NormalTok{dim_grupo1_ }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo2_}
\NormalTok{dim3_i <-}\StringTok{ }\NormalTok{dim2_f }\OperatorTok{+}\DecValTok{1}
\NormalTok{dim3_f <-}\StringTok{ }\NormalTok{dim_grupo1_ }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo2_ }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo3_}



\CommentTok{# Formato de la tabla mediante función kable()}
\CommentTok{# Formato de los dígitos de los campos}
\CommentTok{# Creación del título de la tabla y anotación}
\KeywordTok{kable}\NormalTok{(df_var_cualitativa_table, }\DataTypeTok{digits =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{3}\NormalTok{), }\DataTypeTok{caption =} \StringTok{"-TABLA RESUMEN DE LAS VARIABLES CUALITATIVAS-}
\StringTok{      <p> (Total observaciones: 1309. Suma de frecuencias relativas sin redondeo = 1.000)"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\StringTok{"striped"}\NormalTok{,}
                \DataTypeTok{full_width =}\NormalTok{ F) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Clases Embarque"}\NormalTok{,}
\NormalTok{            dim1_i,}
\NormalTok{            dim1_f,}
            \DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Sexo"}\NormalTok{,}
\NormalTok{            dim2_i,}
\NormalTok{            dim2_f,}
            \DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Embarque"}\NormalTok{,}
\NormalTok{            dim3_i,}
\NormalTok{            dim3_f,}
            \DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:unnamed-chunk-92}-TABLA RESUMEN DE LAS VARIABLES CUALITATIVAS-
      <p> (Total observaciones: 1309. Suma de frecuencias relativas sin redondeo = 1.000)}
\centering
\begin{tabular}[t]{l|r|r}
\hline
Variable Cualitativa & Frecuencia Absoluta & Frecuencia Relativa\\
\hline
\multicolumn{3}{l}{\textbf{Clases Embarque}}\\
\hline
\hspace{1em}1 & 323 & 0.247\\
\hline
\hspace{1em}2 & 277 & 0.212\\
\hline
\hspace{1em}3 & 709 & 0.542\\
\hline
\multicolumn{3}{l}{\textbf{Sexo}}\\
\hline
\hspace{1em}female & 466 & 0.356\\
\hline
\hspace{1em}male & 843 & 0.644\\
\hline
\multicolumn{3}{l}{\textbf{Embarque}}\\
\hline
\hspace{1em}C & 270 & 0.206\\
\hline
\hspace{1em}Q & 123 & 0.094\\
\hline
\hspace{1em}S & 916 & 0.700\\
\hline
\end{tabular}
\end{table}

\hypertarget{tabla-resumen-de-las-variables-cuantitativas-datos-completos}{%
\subsection{Tabla resumen de las variables cuantitativas (datos
completos)}\label{tabla-resumen-de-las-variables-cuantitativas-datos-completos}}

Realizaremos una tabla resumen con los estadísticos principales de
tendencia central y dispersión, con medidas robustas y no robustas. Para
ello, utilizaremos tres funciones que nos aportarán diferentes
estadísticos a utilizar:

describe() winsor.mean() (aplicaremos unos límites del 5 \%).
stat.desc() Estas tres funciones nos darán diversos estadísticos que
uniremos y ordenaremos en una única tabla para mostrar un completo
resumen estadístico de las variables cuantitativas.

Finalmente, creamos una tabla mediante la función kable().

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creación tabla con describe()}
\NormalTok{col_var_cuantitativa_sin_ID <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Age"}\NormalTok{, }\StringTok{"SibSp"}\NormalTok{, }\StringTok{"Parch"}\NormalTok{, }\StringTok{"Count.ticket"}\NormalTok{, }\StringTok{"Unit.price"}\NormalTok{)}

\NormalTok{df_var_cuantitativa <-}\StringTok{ }\NormalTok{df_total_sin_etiqueta[, col_var_cuantitativa_sin_ID]}

\NormalTok{df_var_cuantitativa_tabla <-}\StringTok{ }\KeywordTok{describe}\NormalTok{(df_var_cuantitativa, }\DataTypeTok{quant =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{IQR =} \OtherTok{TRUE}\NormalTok{)}

\CommentTok{# Creación tabla con winsor.mean()}
\NormalTok{winsor <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{t}\NormalTok{(}\KeywordTok{winsor.mean}\NormalTok{(df_var_cuantitativa, }\DataTypeTok{trim=} \FloatTok{0.05}\NormalTok{)))}
\NormalTok{winsor_df <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{t}\NormalTok{(winsor))}
\KeywordTok{colnames}\NormalTok{(winsor_df) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Winsor Mean 5%"}\NormalTok{)}

\CommentTok{# Unión tablas describe() con winsor.mean()}
\NormalTok{df_var_cuantitativa_tabla}\OperatorTok{$}\NormalTok{Winsor_Mean_.}\DecValTok{5}\NormalTok{ <-}\StringTok{ }\NormalTok{winsor_df}\OperatorTok{$}\StringTok{`}\DataTypeTok{Winsor Mean 5%}\StringTok{`}

\CommentTok{# Eliminación campos no usables}
\NormalTok{df_var_cuantitativa_tabla <-}\StringTok{ }\NormalTok{df_var_cuantitativa_tabla[, }\OperatorTok{-}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{15}\NormalTok{ )]}

\CommentTok{# Cambio de nombres de los campos}
\KeywordTok{colnames}\NormalTok{(df_var_cuantitativa_tabla) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Number"}\NormalTok{, }\StringTok{"Mean"}\NormalTok{, }\StringTok{"St_Dev"}\NormalTok{, }\StringTok{"Median"}\NormalTok{, }\StringTok{"Trimmed_Median"}\NormalTok{, }\StringTok{"MAD"}\NormalTok{, }\StringTok{"Min"}\NormalTok{, }\StringTok{"Max"}\NormalTok{, }\StringTok{"Range"}\NormalTok{, }\StringTok{"SE_Mean"}\NormalTok{, }\StringTok{"IQR"}\NormalTok{, }\StringTok{"Winsor_Mean_0.5"}\NormalTok{)}

\NormalTok{df_var_cuantitativa_tabla}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Number  Mean St_Dev Median Trimmed_Median   MAD  Min   Max Range SE_Mean   IQR Winsor_Mean_0.5
## Age            1309 29.56  13.88   27.0          28.93 11.86 0.17 80.00 79.83    0.38 16.00           29.47
## SibSp          1309  0.50   1.04    0.0           0.27  0.00 0.00  8.00  8.00    0.03  1.00            0.39
## Parch          1309  0.39   0.87    0.0           0.18  0.00 0.00  9.00  9.00    0.02  0.00            0.34
## Count.ticket   1309  2.10   1.78    1.0           1.69  0.00 1.00 11.00 10.00    0.05  2.00            2.01
## Unit.price     1309 14.69  11.99    8.3          12.40  3.26 3.17 82.51 79.34    0.33  7.33           14.24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{options}\NormalTok{(}\DataTypeTok{digits=}\DecValTok{2}\NormalTok{)}

\CommentTok{# Creación tabla con stat.desc()}
\NormalTok{df_var_cuantitativa_tabla2 <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{t}\NormalTok{(}\KeywordTok{round}\NormalTok{(}\KeywordTok{stat.desc}\NormalTok{(df_var_cuantitativa),}\DecValTok{2}\NormalTok{)))}

\CommentTok{# Cambio de nombres de los campos}
\KeywordTok{colnames}\NormalTok{(df_var_cuantitativa_tabla2) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"tot_num"}\NormalTok{, }\StringTok{"NUll"}\NormalTok{, }\StringTok{"NA"}\NormalTok{, }\StringTok{"Min_"}\NormalTok{, }\StringTok{"Max_"}\NormalTok{, }\StringTok{"Range_"}\NormalTok{, }\StringTok{"sum"}\NormalTok{, }\StringTok{"median_"}\NormalTok{, }\StringTok{"mean_"}\NormalTok{, }\StringTok{"se_mean_"}\NormalTok{, }\StringTok{"CI_Mean_0.95"}\NormalTok{, }\StringTok{"Var"}\NormalTok{, }\StringTok{"stddev_"}\NormalTok{, }\StringTok{"Coef_Var"}\NormalTok{)}

\CommentTok{# Eliminación campos no usables}
\NormalTok{df_var_cuantitativa_tabla2 <-}\StringTok{ }\NormalTok{df_var_cuantitativa_tabla2[, }\OperatorTok{-}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{ ,}\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{9}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{13}\NormalTok{)]}
\NormalTok{df_var_cuantitativa_tabla2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              NA CI_Mean_0.95    Var Coef_Var
## Age           0         0.75 192.67     0.47
## SibSp         0         0.06   1.09     2.09
## Parch         0         0.05   0.75     2.25
## Count.ticket  0         0.10   3.17     0.85
## Unit.price    0         0.65 143.86     0.82
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Unión tablas describe()/winsor.mean() con tabla stat.desc()}
\NormalTok{counterdf_cuan <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\KeywordTok{dim}\NormalTok{(df_var_cuantitativa_tabla2)[}\DecValTok{2}\NormalTok{])}
\NormalTok{df_var_cuantitativa_tabla_dim_ini <-}\StringTok{ }\KeywordTok{dim}\NormalTok{(df_var_cuantitativa_tabla)[}\DecValTok{2}\NormalTok{]}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in}\NormalTok{ counterdf_cuan)\{}
\NormalTok{      df_var_cuantitativa_tabla[i}\OperatorTok{+}\NormalTok{df_var_cuantitativa_tabla_dim_ini] <-}\StringTok{ }\NormalTok{df_var_cuantitativa_tabla2[i]}
\NormalTok{     \}}

\CommentTok{# Reordenamiento de las columnas para poder agrupar los campos for temática: tendencia central, dispersión, robusta y no robusta}
\NormalTok{df_var_cuantitativa_tabla <-}\StringTok{ }\NormalTok{df_var_cuantitativa_tabla[, }\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{14}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{16}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{13}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{9}\NormalTok{)]}


\CommentTok{# Creación del dataframe haciendo la transpuesta de la tabla anterior para tener los estadisticos en las fila y las variables en las columnas.}
\NormalTok{df_var_cuantitativa_tabla <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{t}\NormalTok{(df_var_cuantitativa_tabla))}
\NormalTok{df_var_cuantitativa_tabla}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                     Age   SibSp   Parch Count.ticket Unit.price
## Mean              29.56 5.0e-01 3.9e-01      2.1e+00      14.69
## SE_Mean            0.38 2.9e-02 2.4e-02      4.9e-02       0.33
## CI_Mean_0.95       0.75 6.0e-02 5.0e-02      1.0e-01       0.65
## Median            27.00 0.0e+00 0.0e+00      1.0e+00       8.30
## Trimmed_Median    28.93 2.7e-01 1.8e-01      1.7e+00      12.40
## Winsor_Mean_0.5   29.47 3.9e-01 3.4e-01      2.0e+00      14.24
## Var              192.67 1.1e+00 7.5e-01      3.2e+00     143.86
## Coef_Var           0.47 2.1e+00 2.2e+00      8.5e-01       0.82
## St_Dev            13.88 1.0e+00 8.7e-01      1.8e+00      11.99
## MAD               11.86 0.0e+00 0.0e+00      0.0e+00       3.26
## IQR               16.00 1.0e+00 0.0e+00      2.0e+00       7.33
## Number          1309.00 1.3e+03 1.3e+03      1.3e+03    1309.00
## NA                 0.00 0.0e+00 0.0e+00      0.0e+00       0.00
## Min                0.17 0.0e+00 0.0e+00      1.0e+00       3.17
## Max               80.00 8.0e+00 9.0e+00      1.1e+01      82.51
## Range             79.83 8.0e+00 9.0e+00      1.0e+01      79.34
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creación de la tabla mediante kable()}

\CommentTok{# Formato numérico no científico}
\KeywordTok{options}\NormalTok{(}\DataTypeTok{scipen =} \DecValTok{999}\NormalTok{)}

\CommentTok{# Variables auxiliares para la creación de la tabla kable() de forma más automática.}
\CommentTok{# Dimensiones de cada grupo de la tabla}
\NormalTok{dim_grupo1 =}\StringTok{ }\DecValTok{3}
\NormalTok{dim_grupo2 =}\StringTok{ }\DecValTok{3}
\NormalTok{dim_grupo3 =}\StringTok{ }\DecValTok{3}
\NormalTok{dim_grupo4 =}\StringTok{ }\DecValTok{2}
\NormalTok{dim_grupo5 =}\StringTok{ }\DecValTok{5}

\CommentTok{# Límites de las posiciones de los grupos (automatico)}
\NormalTok{dim1_i <-}\StringTok{ }\DecValTok{1}
\NormalTok{dim1_f <-}\StringTok{ }\NormalTok{dim_grupo1}
\NormalTok{dim2_i <-}\StringTok{ }\NormalTok{dim1_f }\OperatorTok{+}\DecValTok{1}
\NormalTok{dim2_f <-}\StringTok{ }\NormalTok{dim_grupo1 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo2}
\NormalTok{dim3_i <-}\StringTok{ }\NormalTok{dim2_f }\OperatorTok{+}\DecValTok{1}
\NormalTok{dim3_f <-}\StringTok{ }\NormalTok{dim_grupo1 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo2 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo3}
\NormalTok{dim4_i <-}\StringTok{ }\NormalTok{dim3_f }\OperatorTok{+}\DecValTok{1}
\NormalTok{dim4_f <-}\StringTok{ }\NormalTok{dim_grupo1 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo2 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo3 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo4}
\NormalTok{dim5_i <-}\StringTok{ }\NormalTok{dim4_f }\OperatorTok{+}\DecValTok{1}
\NormalTok{dim5_f <-}\StringTok{ }\NormalTok{dim_grupo1 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo2 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo3 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo4 }\OperatorTok{+}\StringTok{ }\NormalTok{dim_grupo5}

\CommentTok{# Formato de la tabla mediante función kable()}
\CommentTok{# Formato de los dígitos de los campos}
\CommentTok{# Creación del título de la tabla y anotación}
\KeywordTok{kable}\NormalTok{(df_var_cuantitativa_tabla, }\DataTypeTok{digits =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{), }\DataTypeTok{caption =} \StringTok{"-TABLA RESUMEN DE LAS VARIABLES CUANTITATIVAS-}
\StringTok{      <p> (Total observaciones: 1309.)"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\StringTok{"striped"}\NormalTok{,  }\DataTypeTok{full_width =}\NormalTok{ F) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Tendencia Central (medidas  NO robustas)"}\NormalTok{,}
\NormalTok{            dim1_i,}
\NormalTok{            dim1_f,}
            \DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Tendencia Central (medidas robustas)"}\NormalTok{,}
\NormalTok{            dim2_i,}
\NormalTok{            dim2_f,}
            \DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Dispersion (medidas NO robustas)"}\NormalTok{,}
\NormalTok{            dim3_i,}
\NormalTok{            dim3_f,}
            \DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Dispersion (medidas robustas)"}\NormalTok{,}
\NormalTok{            dim4_i,}
\NormalTok{            dim4_f,}
            \DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{pack_rows}\NormalTok{(}\StringTok{"Información Adicional"}\NormalTok{, dim5_i, dim5_f ,}\DataTypeTok{label_row_css =} \StringTok{"background-color: #666; color: #fff;"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:unnamed-chunk-96}-TABLA RESUMEN DE LAS VARIABLES CUANTITATIVAS-
      <p> (Total observaciones: 1309.)}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
  & Age & SibSp & Parch & Count.ticket & Unit.price\\
\hline
\multicolumn{6}{l}{\textbf{Tendencia Central (medidas  NO robustas)}}\\
\hline
\hspace{1em}Mean & 29.56 & 0.50 & 0.39 & 2.102 & 14.69\\
\hline
\hspace{1em}SE\_Mean & 0.38 & 0.03 & 0.02 & 0.049 & 0.33\\
\hline
\hspace{1em}CI\_Mean\_0.95 & 0.75 & 0.06 & 0.05 & 0.100 & 0.65\\
\hline
\multicolumn{6}{l}{\textbf{Tendencia Central (medidas robustas)}}\\
\hline
\hspace{1em}Median & 27.00 & 0.00 & 0.00 & 1.000 & 8.30\\
\hline
\hspace{1em}Trimmed\_Median & 28.93 & 0.27 & 0.18 & 1.689 & 12.40\\
\hline
\hspace{1em}Winsor\_Mean\_0.5 & 29.47 & 0.39 & 0.34 & 2.008 & 14.24\\
\hline
\multicolumn{6}{l}{\textbf{Dispersion (medidas NO robustas)}}\\
\hline
\hspace{1em}Var & 192.67 & 1.09 & 0.75 & 3.170 & 143.86\\
\hline
\hspace{1em}Coef\_Var & 0.47 & 2.09 & 2.25 & 0.850 & 0.82\\
\hline
\hspace{1em}St\_Dev & 13.88 & 1.04 & 0.87 & 1.780 & 11.99\\
\hline
\multicolumn{6}{l}{\textbf{Dispersion (medidas robustas)}}\\
\hline
\hspace{1em}MAD & 11.86 & 0.00 & 0.00 & 0.000 & 3.26\\
\hline
\hspace{1em}IQR & 16.00 & 1.00 & 0.00 & 2.000 & 7.33\\
\hline
\multicolumn{6}{l}{\textbf{Información Adicional}}\\
\hline
\hspace{1em}Number & 1309.00 & 1309.00 & 1309.00 & 1309.000 & 1309.00\\
\hline
\hspace{1em}NA & 0.00 & 0.00 & 0.00 & 0.000 & 0.00\\
\hline
\hspace{1em}Min & 0.17 & 0.00 & 0.00 & 1.000 & 3.17\\
\hline
\hspace{1em}Max & 80.00 & 8.00 & 9.00 & 11.000 & 82.51\\
\hline
\hspace{1em}Range & 79.83 & 8.00 & 9.00 & 10.000 & 79.34\\
\hline
\end{tabular}
\end{table}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Creación tabla con describe()}
\CommentTok{#col_var_cuantitativa_ID <- c("Age", "SibSp", "Parch", "Fare")}

\CommentTok{#df_var_cuantitativa <- df_total_sin_etiqueta[, col_var_cuantitativa_ID]}

\CommentTok{#df_var_cuantitativa_tabla <- describe(df_var_cuantitativa, quant = TRUE, IQR = TRUE)}

\CommentTok{# Eliminación campos no usables}
\CommentTok{#df_var_cuantitativa_tabla <- df_var_cuantitativa_tabla[, -c(1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 15)]}

\CommentTok{# Cambio de nombres de los campos}
\CommentTok{#colnames(df_var_cuantitativa_tabla) <- c("Mean", "St_Dev", "Median","IQR")}

\CommentTok{# Transpuesta de la matriz}
\CommentTok{#df_var_cuantitativa_tabla <- data.frame(t(df_var_cuantitativa_tabla))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Selección/Filtrado de las instancias que solamente pertenecen a US}
\CommentTok{# Creación de la tabla mediante kable()}

\CommentTok{# Formato numérico no científico}
\CommentTok{#options(scipen = 999)}

\CommentTok{# Variables auxiliares para la creación de la tabla kable() de forma más automática.}
\CommentTok{# Dimensiones de cada grupo de la tabla}
\CommentTok{#dim_grupo1 = 4}


\CommentTok{# Límites de las posiciones de los grupos (automatico)}
\CommentTok{#dim1_i <- 1}
\CommentTok{#dim1_f <- dim_grupo1}


\CommentTok{# Formato de la tabla mediante función kable()}
\CommentTok{# Formato de los dígitos de los campos}
\CommentTok{# Creación del título de la tabla y anotación}
\CommentTok{#kable(df_var_cuantitativa_tabla, digits = c(2, 2, 2, 2, 2, 2, 2), caption = "TABLA RESUMEN DE LAS VARIABLES CUANTITATIVAS (Total observaciones: 400)}
\CommentTok{#            __________________________________________________________________________________}
\CommentTok{#      <p>   Sales:         Ventas unitarias, en miles, en cada ubicación}
\CommentTok{#      <p>   CompPrice:     Precio que cobra el competidor en cada ubicación}
\CommentTok{#      <p>   Income:        Nivel de ingresos comunitarios, en miles de dólares}
\CommentTok{#      <p>   Advertising:   Presupuesto de publicidad local de la empresa en cada ubicación, en miles de dólares}
\CommentTok{#      <p>   Population:    Tamaño de la población en la región, en miles}
\CommentTok{#      <p>   Price:         Precio del producto en cada ubicación}
\CommentTok{#      <p>   Age:           Edad media de la población local") %>%}
\CommentTok{#  }
\CommentTok{#  kable_styling("striped",  full_width = T) %>%}
\CommentTok{#  pack_rows("Datos Cuantitativos",}
\CommentTok{#            dim1_i,}
\CommentTok{#            dim1_f,}
\CommentTok{#            label_row_css = "background-color: #666; color: #fff;")}
\end{Highlighting}
\end{Shaded}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{resoluciuxf3n-del-problema}{%
\section{\texorpdfstring{\textbf{Resolución del
problema}}{Resolución del problema}}\label{resoluciuxf3n-del-problema}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{creaciuxf3n-del-archivo-preprocesado}{%
\section{\texorpdfstring{\textbf{Creación del archivo
preprocesado}}{Creación del archivo preprocesado}}\label{creaciuxf3n-del-archivo-preprocesado}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Guardamos el archivo con el nombre Titanic_processed.csv}
\CommentTok{#write.csv(df, "Titanic_processed.csv", row.names = FALSE)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{contrib <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{rbind}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{"Investigación Previa"}\NormalTok{, }\StringTok{"Olga Garcés / Carlos Acosta"}\NormalTok{),}
                            \KeywordTok{c}\NormalTok{(}\StringTok{"Redacción de las respuestas"}\NormalTok{, }\StringTok{"Olga Garcés / Carlos Acosta"}\NormalTok{),}
                            \KeywordTok{c}\NormalTok{(}\StringTok{"Desarrollo código", "}\NormalTok{Olga Garcés }\OperatorTok{/}\StringTok{ }\NormalTok{Carlos Acosta}\StringTok{")))}
\StringTok{colnames(contrib) <- c("}\NormalTok{Contribuciones}\StringTok{", "}\NormalTok{Firma}\StringTok{")}

\StringTok{contrib}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Contribuciones                       Firma
## 1        Investigación Previa Olga Garcés / Carlos Acosta
## 2 Redacción de las respuestas Olga Garcés / Carlos Acosta
## 3           Desarrollo código Olga Garcés / Carlos Acosta
\end{verbatim}

\end{document}
