---
title: "**M2.851 – TIPOLOGÍA Y CICLO DE VIDA DE LOS DATOS: PRA 2**"
author: "Olga Garcés Ciemerozum / Carlos Acosta Quintas"
date: 'Junio 2021'
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 4

     
---

<style>
body {
text-align: justify}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
options(width = 500)

```

<br><br><br>

CHANGE HERE
******
# **Carga de librerias**
******

```{r load_libraries, message=FALSE, warning=FALSE, include=FALSE}
# Cargamos las librerias de  R que vamos a usar
library("ISLR")
library("SmartEDA")
library("tidyverse")
library(DT) # Para visualizar tablas
library(readr)
library(plyr)
library (MASS)
library(ggpubr) # Para QQ plot
library(ggplot2) # Para graficos
# library(stringr) #Para str_to_title()
# library(reshape) #Para Pivot Tables
# library(VIM) # Para kNN
library(psych) # Para Grafico Correlaciones
library(pastecs) #Para tabla resumen cuantitativa
library(gmodels) #Para tabla resumen cualiativa
library(knitr) #Para Kable
library(kableExtra) #Para Kable
library(hrbrthemes) #Para gráficos densidades
library(dplyr) #Para gráficos densidades
library(vioplot) #Para gráficos violin
library(PASWR) #Estadístico z
library(BSDA) #Estadístico z.test
library(lsr) #Eta2
library(faraway) #Multicolinealidad
library(gridExtra) #Grid graficas
library(corrplot) #Plot para correlaciones
library(ResourceSelection) #Hosmer Lemeshowi
library(InformationValue) #ROC
library(plotROC)#ROC
library(DescTools) #Scheffe test
```

<br><br><br>


******
# **Descripción del dataset**
******

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Carga del archivo que contiene el dataframe
df <- read.csv("Carseats.csv")
```

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Estructura del archivo que contiene el dataframe
str(df)
```
```{r echo=TRUE, message=FALSE, warning=FALSE}
# Primeras líneas de los datos
head(df)
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
# Sustitución de las variables tipo char por variables categóricas.

df$ShelveLoc <- as.factor(df$ShelveLoc)
df$Urban <- as.factor(df$Urban)
df$US <- as.factor(df$US)
df$Education <- factor(df$Education, levels = c(10, 11, 12, 13, 14, 15, 16, 17, 18))

```


```{r echo=TRUE, message=FALSE, warning=FALSE}
# Exploración del resumen de los datos de las variables del dataframe 
sapply(df, summary)
```


```{r }
# Overview of the data - Type = 1
ExpData(data=df,type=1)

# Structure of the data - Type = 2
ExpData(data=df,type=2)

```

******
# **Integración y selección de los datos**
******


## **Integración de los Datos**





## **Selección de los Datos**


```{r echo=TRUE, message=FALSE, warning=FALSE, include=TRUE}
# Creación tabla con describe()
col_var_cuantitativa_sin_ID <- c("Sales", "CompPrice", "Income", "Advertising", "Population", "Price", "Age")

df_var_cuantitativa <- df[, col_var_cuantitativa_sin_ID]

df_var_cuantitativa_tabla <- describe(df_var_cuantitativa, quant = TRUE, IQR = TRUE)

# Eliminación campos no usables
df_var_cuantitativa_tabla <- df_var_cuantitativa_tabla[, -c(1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 15)]

# Cambio de nombres de los campos
colnames(df_var_cuantitativa_tabla) <- c("Mean", "St_Dev", "Median","IQR")

# Transpuesta de la matriz
df_var_cuantitativa_tabla <- data.frame(t(df_var_cuantitativa_tabla))
df_var_cuantitativa_tabla
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
# Selección/Filtrado de las instancias que solamente pertenecen a US
# Creación de la tabla mediante kable()

# Formato numérico no científico
options(scipen = 999)

# Variables auxiliares para la creación de la tabla kable() de forma más automática.
# Dimensiones de cada grupo de la tabla
dim_grupo1 = 4


# Límites de las posiciones de los grupos (automatico)
dim1_i <- 1
dim1_f <- dim_grupo1


# Formato de la tabla mediante función kable()
# Formato de los dígitos de los campos
# Creación del título de la tabla y anotación
kable(df_var_cuantitativa_tabla, digits = c(2, 2, 2, 2, 2, 2, 2), caption = "TABLA RESUMEN DE LAS VARIABLES CUANTITATIVAS (Total observaciones: 400)
            __________________________________________________________________________________
      <p>   Sales:         Ventas unitarias, en miles, en cada ubicación
      <p>   CompPrice:     Precio que cobra el competidor en cada ubicación
      <p>   Income:        Nivel de ingresos comunitarios, en miles de dólares
      <p>   Advertising:   Presupuesto de publicidad local de la empresa en cada ubicación, en miles de dólares
      <p>   Population:    Tamaño de la población en la región, en miles
      <p>   Price:         Precio del producto en cada ubicación
      <p>   Age:           Edad media de la población local") %>%
  
  kable_styling("striped",  full_width = T) %>%
  pack_rows("Datos Cuantitativos",
            dim1_i,
            dim1_f,
            label_row_css = "background-color: #666; color: #fff;")
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
# Boxplot Advertising
boxplot(df$Advertising)
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
# Selección/Filtrado de las instancias que solamente pertenecen a US
df <- filter(df, US=="Yes")
df
```



```{r echo=TRUE, message=FALSE, warning=FALSE}
df$SalesValue <- df$Sales*df$Price
df$Profit <- df$Sales*df$Price - df$Advertising*1000
```

```{r echo=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=TRUE, message=FALSE, warning=FALSE}

```

```{r echo=TRUE, message=FALSE, warning=FALSE}

```


******
# **Limpieza de datos**
******

## **Datos con ceros o vacíos**

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Comprobacion registros nulos.
sum(is.na(df))
```


```{r echo=TRUE, message=FALSE, warning=FALSE}
# Comprobacion registros iguales a cero.

# IMPLEMENTAR FUNCION
```

## **Datos con valores extremos**



```{r , fig.height=4, fig.width=6}
# Boxplot variable Sales
boxplot(df$Sales, main="Boxplot Variable Sales",ylab="Dólares")
boxplot.stats(df$Sales, coef = 1.5, do.conf = TRUE, do.out = TRUE)
```


```{r , fig.height=4, fig.width=6}
# Boxplot variable CompPrice
boxplot(df$CompPrice, main="Boxplot Variable CompPrice",ylab="Dólares")
boxplot.stats(df$CompPrice, coef = 1.5, do.conf = TRUE, do.out = TRUE)
```


```{r , fig.height=4, fig.width=6}
# Boxplot variable Income
boxplot(df$Income, main="Boxplot Variable Income",ylab="Dólares")
boxplot.stats(df$Income, coef = 1.5, do.conf = TRUE, do.out = TRUE)
```

```{r , fig.height=4, fig.width=6}
# Boxplot variable Advertising
boxplot(df$Advertising, main="Boxplot Variable Advertising",ylab="Dólares")
boxplot.stats(df$Advertising, coef = 1.5, do.conf = TRUE, do.out = TRUE)
```


```{r , fig.height=4, fig.width=6}
# Boxplot variable Population
boxplot(df$Population, main="Boxplot Variable Population",ylab="Personas (miles)")
boxplot.stats(df$Population, coef = 1.5, do.conf = TRUE, do.out = TRUE)
```

```{r , fig.height=4, fig.width=6}
# Boxplot variable Price
boxplot(df$Price, main="Boxplot Variable Price",ylab="Dólares")
boxplot.stats(df$Price, coef = 1.5, do.conf = TRUE, do.out = TRUE)
```


```{r , fig.height=4, fig.width=6}
# Boxplot variable Age
boxplot(df$Age, main="Boxplot Variable Age",ylab="Edad (años)")
boxplot.stats(df$Age, coef = 1.5, do.conf = TRUE, do.out = TRUE)
```




******
# **Análisis de datos**
******



******
# **Representación de resultados**
******



******
# **Resolución del problema**
******


******
# **Creación del archivo preprocesado**
******

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Guardamos el archivo con el nombre Carseats_processed.csv
write.csv(df, "Carseats_processed.csv", row.names = FALSE)
```


<br>


